### PR TITLE
Added ping functionalty to nxos driver

### PR DESCRIPTION
**Pull request by arandomguybr**
<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

### CODE REVIEW

**Comment by dbarrosop** [comment]
nice! first PR agains the new codebase :P Will hold onto this one though until we get the first official release. We are still in "beta". Probably end of next week.

**Comment by dbarrosop** [comment]
@arandomguybr two comments:

1. You have to add a test case
2. pylama doesn't seem happy about some formatting issue

**Comment by arandomguybr** [comment]
@dbarrosop, I will fix the formatting issue. 
Regarding the test case, would you guys help me out ? I really don't know how to proceed with that one. 
@ktbyers also said on the slack channel he could give some guidance on the tests.

**Comment by bewing** [comment]
The napalm test framework automatically generates unit tests based on mocked data stored in `test/<driver>/mocked_data/test_<method>/<test name>/`

In this case, you'll need to create `test/nxos/test_ping/normal/`.

If you run tests after that, it will start generating more specific errors:
* First it will complain it can't find file it's trying to load mocked data from.   Create a device and store the output of the specific command in the correct format in the file.
* Then it will complain that it can't load the expected result.  Create the expected_result.json file with what the function SHOULD return, based on the mocked input data.

**Comment by mirceaulinic** [comment]
Hi @arandomguybr - did you see @bewing's comment above? Thanks!

**Comment by mirceaulinic** [comment]
Bump @arandomguybr

**Comment by mirceaulinic** [comment]
Bump @arandomguybr

**Comment by mirceaulinic** [comment]
This PR seems to be stale and I ported @arandomguybr's commits into https://github.com/napalm-automation/napalm/pull/641.

**Pull request closed without merging**
