### PR TITLE
NX-OS refactor

### PR DESCRIPTION
**Pull request by ktbyers**
I want to release napalm 2.3.3 before merging this.

This is a big change to both the NX-OS drivers

- Refactor SCP to use Netmiko
- Significantly reduce redundant code between two drivers
- Use standardized file names for rollback file and replace file (same file names as IOS)
- Added a platform attribute to indicate 'nxos', 'ios', 'junos' et cetera
- Improve NX-OS merge atomic behavior
- Making it easier for potentially future adding a get_file and put_file using Netmiko
- Making it easier for potentially adding XML support in NX-OS (and replacing/elminating NX-OS jsonrpc and SSH support).
- Also fixes issues #475 #447 #474

### CODE REVIEW

**Comment by ktbyers** [comment]
Ran napalm_custom_test on nxos and nxos_ssh for this updated driver. I also did quite a bit of testing using pdb and a real device.

https://github.com/ktbyers/napalm_custom_test

**Comment by ktbyers** [comment]
Added unit tests to test that automatic rollback on a failed merge operation worked properly for NX-OS (this is in the testing against real devices). Currently, I only ran it as a one off test; not running on an ongoing basis (it has to be merged into 'develop' before I can test on an ongoing basis).

https://github.com/ktbyers/napalm_custom_test/commit/37a961fb6595b74b0e90360fb72126c25874e4a6#diff-16b358213f85e70673686e009a79b591R93

**Comment by mattschwen** [comment]
+1 

I have reviewed the code briefly for a sanity check and have tested the PR changes against physical hardware. I used multiple getters for `NXOS` and `NXOS_SSH` as well as config operations on both `9K` and `5k` with no tracebacks or odd behavior.

**Review by bewing — APPROVED** [review]
LGTM.

**Pull request merged**
