### PR TITLE
JunOS discard config if loading fails, fixes #1445

### LINKED ISSUE #1445: JunOS failed commits causes lingering config sessions that are not cleared
### JunOS failed commits causes lingering config sessions that are not cleared 

When doing load_replace_candidate and the candidate configuration has a syntax error, napalm will raise a ReplaceConfigException as expected. However, the failed candidate configuration is not cleared from the router and instead lingers causing future commits to fail. The next attempt at a commit will result in napalm.base.exceptions.LockError and you have to manually log in to the network device and run "request system logout pid <pid>". This behavior differs from the EOS driver in NAPALM for example, which seems to run "discard_config()" after a failed configuration. I think the same should be done in the junos driver, doing a rollback 0 should accomplish the same thing as I understand it. I don't see any reason to lock any future attempts to commit configuration because of a past syntax error.  There is a sorf-of workaround possible by changing the configuration to private instead of exclusive, which will allow future commits but still not clear the failed sessions so you will probably run in to an issue with too many sessions after a while.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==3.2.0
nornir-napalm==0.1.1
junos-eznc==2.5.4
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Junos: 20.4R1-S1.2
```

### Error Traceback

Commit with syntax error, expected output:

```
Traceback (most recent call last):
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/device.py", line 837, in execute
    filter_xml=kvargs.get("filter_xml"),
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/decorators.py", line 165, in wrapper
    raise ex
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/decorators.py", line 117, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/device.py", line 1440, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e, filter_xml)._NCElement__doc
  File "/opt/cnaas/venv/lib/python3.7/site-packages/ncclient/manager.py", line 292, in rpc
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 506, in request
    return self._request(node)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 365, in _request
    raise RPCError(to_ele(self._reply._raw), errs=errors)
ncclient.operations.rpc.RPCError: error: syntax error
error: error recovery ignores input until this point

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/utils/config.py", line 491, in try_load
    rpc_contents, ignore_warning=ignore_warning, **rpc_xattrs
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/rpcmeta.py", line 288, in load_config
    return self._junos.execute(rpc, ignore_warning=ignore_warning)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/device.py", line 854, in execute
    raise EzErrors.RpcError(cmd=rpc_cmd_e, rsp=rsp, errs=ex)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: syntaxerror, message: error: syntax error
error: error recovery ignores input until this point)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cnaas/venv/lib/python3.7/site-packages/napalm/junos/junos.py", line 253, in _load_candidate
    ignore_warning=self.ignore_warning,
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/utils/config.py", line 579, in load
    return try_load(rpc_contents, rpc_xattrs, ignore_warning=ignore_warning)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/utils/config.py", line 496, in try_load
    raise ConfigLoadError(cmd=err.cmd, rsp=err.rsp, errs=err.errs)
jnpr.junos.exception.ConfigLoadError: ConfigLoadError(severity: error, bad_element: syntaxerror, message: error: syntax error
error: error recovery ignores input until this point)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cnaas/venv/lib/python3.7/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 32, in napalm_configure
    device.load_replace_candidate(filename=filename, config=configuration)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/napalm/junos/junos.py", line 264, in load_replace_candidate
    self._load_candidate(filename, config, True)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/napalm/junos/junos.py", line 257, in _load_candidate
    raise ReplaceConfigException(e.errs)
napalm.base.exceptions.ReplaceConfigException: [{'severity': 'error', 'source': None, 'edit_path': None, 'bad_element': 'syntaxerror', 'message': 'syntax error'}, {'severity': 'error', 'source': None, 'edit_path': None, 'bad_element': '}', 'message': 'error recovery ignores input until this point'}]

```

Following commit, fails for strange reasons:

```
Traceback (most recent call last):
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/device.py", line 837, in execute
    filter_xml=kvargs.get("filter_xml"),
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/decorators.py", line 165, in wrapper
    raise ex
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/decorators.py", line 117, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/device.py", line 1440, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e, filter_xml)._NCElement__doc
  File "/opt/cnaas/venv/lib/python3.7/site-packages/ncclient/manager.py", line 292, in rpc
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 506, in request
    return self._request(node)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 367, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: 
configuration database locked by:
  admin terminal  (pid 32260) on since 2021-05-06 11:04:06 UTC, idle 00:04:48
      exclusive 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/utils/config.py", line 603, in lock
    self.rpc.lock_configuration()
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/rpcmeta.py", line 364, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/device.py", line 854, in execute
    raise EzErrors.RpcError(cmd=rpc_cmd_e, rsp=rsp, errs=ex)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: configuration database locked by:
  admin terminal  (pid 32260) on since 2021-05-06 11:04:06 UTC, idle 00:04:48
      exclusive)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cnaas/venv/lib/python3.7/site-packages/napalm/junos/junos.py", line 150, in _lock
    self.device.cu.lock()
  File "/opt/cnaas/venv/lib/python3.7/site-packages/jnpr/junos/utils/config.py", line 606, in lock
    raise LockError(rsp=err.rsp)
jnpr.junos.exception.LockError: LockError(severity: error, bad_element: None, message: configuration database locked by:
  admin terminal  (pid 32260) on since 2021-05-06 11:04:06 UTC, idle 00:04:48
      exclusive)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cnaas/venv/lib/python3.7/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 32, in napalm_configure
    device.load_replace_candidate(filename=filename, config=configuration)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/napalm/junos/junos.py", line 264, in load_replace_candidate
    self._load_candidate(filename, config, True)
  File "/opt/cnaas/venv/lib/python3.7/site-packages/napalm/junos/junos.py", line 234, in _load_candidate
    self._lock()
  File "/opt/cnaas/venv/lib/python3.7/site-packages/napalm/junos/junos.py", line 153, in _lock
    raise LockError(str(jle))
napalm.base.exceptions.LockError: LockError(severity: error, bad_element: None, message: configuration database locked by:
  admin terminal  (pid 32260) on since 2021-05-06 11:04:06 UTC, idle 00:04:48
      exclusive)
```

### PR DESCRIPTION
**Pull request by indy-independence**
Discard config if there was an error. This avoids stale config sessios lingering on the device after config load fails. Discussed in issue #1445

### CODE REVIEW

**Review by mirceaulinic — CHANGES_REQUESTED** [review]
Thanks for this patch @indy-independence. As discussed, would you be able to apply the same changes for the other drivers to ensure consistency?

**Comment by indy-independence** [comment]
Sorry I'm not familiar with the other device drivers and I don't have lab access to those devices, but from I know about the classic IOS one it doesn't support candidate configs in the device per se so I suppose it will not run in to this issue? Might be an issue on NX OS or IOS-XR though

**Comment by indy-independence** [comment]
The ios-xr netconf driver uses something called _error_option="rollback-on-error"_ in the load_merge_candidate() function which sounds like it would fix this kind of thing, but I haven't tested it

**Comment by indy-independence** [comment]
@mirceaulinic is there something more I should do?

**Comment by mirceaulinic** [comment]
Not sure if you or someone else, but like I said, this needs to be implemented consistently across all the drivers @indy-independence. :)

**Comment by indy-independence** [comment]
@mirceaulinic is it a requirement that all behavior should aligned in the same PR? I mean if Arista and XR does it one way, could we change Juniper to do it the same way now or should we wait (a possibly very long time) until someone who has other devices comes and find this issue and verifies and/or changes behavior for remaining platforms in this same PR?

**Comment by mirceaulinic** [comment]
Not the same PR, but I want to ensure we don't introduce (more) inconsistent behaviour into the `develop` branch. If we'd do so, it'll block future releases, as you said, for a possibly very long time until someone fixes the other platforms. That said, this PR will stay open till we have the code for the other platforms (in this PR or others). What we did in the past was creating a separate branch where we merged the fixes for each individual platform as they've been submitted; once we ha the code for all the platforms, we merged that branch into `develop` then eventually release. Would that work for you?

**Comment by indy-independence** [comment]
I'm not familiar with working on this project so thank you for taking the time to explain! Yes merging in to a separate branch sounds like a good plan to keep all the changes together and synchronized.
This PR and related issue specifically mentions just JunOS, should I create separate issues to investigate the behavior for other platforms?

**Review by mirceaulinic — APPROVED** [review]
Ok, I'm fine to go ahead with this, but the problem may continue to exist on the other platforms, so I suggest to keep the issue open.

> Seems like people don't run in to this issue on other platforms, so maybe it's not an issue anywhere else other than junos-driver?

@indy-independence this assumption doesn't really make a lot of sense, as until you reported it, we weren't aware of Junos either, so that's not something to rely on.

**Pull request merged**
