### PR TITLE
For Vlan interfaces, the driver "nxos", the state is not determined correctly

### PR DESCRIPTION
**Pull request by VictorPavlushin**
For Vlan interfaces, the state is not correctly defined.
There are no admin_state and state fields for them.
Example:
{
  "interface": "Vlan120",
  "svi_admin_state": "up",
  "svi_line_proto": "up",
  "svi_mac": "002a.6ad3.0000",
  "svi_desc": "",
  "svi_ip_addr": "192.168.0.10",
  "svi_ip_mask": "24",
  "svi_mtu": "1500",
  "svi_bw": "1000000",
  "svi_delay": "10"
},
{
  "interface": "Vlan198",
  "svi_admin_state": "down",
  "state_rsn_desc": "Administratively down",
  "svi_line_proto": "down",
  "svi_mac": "002a.6ad3.0000",
  "svi_ip_addr": "192.168.0.11",
  "svi_ip_mask": "24",
  "svi_mtu": "1500",
  "svi_bw": "1000000",
  "svi_delay": "10"
},

### CODE REVIEW

**Comment by ktbyers** [comment]
Okay, thanks for the PR--can you add unit test data to cover this case:

You should make a new directory in this folder:

```
napalm/test/nxos/mocked_data/test_get_interfaces
```

You can use the `normal` folder as an example for what you need to create (but with test data that covers this situation).

It also looks like you need to run `black` on the files you are modifying (as the linter/black check is failing).

Regards, Kirk

**Comment by VictorPavlushin** [comment]
Added processing speed, mac address and description for the Vlan type interface

**Comment by VictorPavlushin** [comment]
This is only a nxos driver problem, since nxos_ssh parsed text and not json.
Re-checked on the piece of iron.

**Comment by VictorPavlushin** [comment]
Update https://github.com/napalm-automation/napalm/pull/1072

**Pull request closed without merging**
