### PR TITLE
Method get_ntp_peers() defined of JunOS, NXOS, EOS & IOS-XR

### PR DESCRIPTION
**Pull request by mirceaulinic**
Child of #154

### CODE REVIEW

**Comment by dbarrosop** [comment]
Seems that we really messed it up, we got another conflict... Sorry about this.

**Comment by jejenone** [comment]
rebased and cleaned.

**Comment by dbarrosop** [comment]
Could you rebase again, please?

**Comment by mirceaulinic** [comment]
Rebased, but check failed: no rake file (https://travis-ci.org/napalm-automation/napalm/builds/110684800#L149)

**Comment by mirceaulinic** [comment]
Ah, not here (facepalm)...

**Comment by dbarrosop** [comment]
Yes, we just implemented that. Can you rebase, please? You will have to add the tests to travis configuration. Check PR #195 for more info.

**Comment by mirceaulinic** [comment]
Will rebase after next merge better? @dbarrosop, @fooelisa great job with the travis tests!

**Pull request merged**
