### PR TITLE
(eos) loop through loaded config to convert HEREDOC commands.  Fixes #519

### LINKED ISSUE #519: EOSDriver._load_config() doesn't support HEREDOC syntax
If attempting to blindly copy a multiline command from a potential config to a file, conversion is required.
```
with EOSDriver(s, u, p) as d:
    load_merge_candidate(config="banner login\nTHIS IS MY BANNER\nEOF")
...
MergeConfigException: Error [1002]: CLI command 4 of 5 'THIS IS MY BANNER' failed: invalid command [Invalid input (at token 0: 'THIS')]
```

### PR DESCRIPTION
**Pull request by bewing**
Discussion welcomed.

### CODE REVIEW

**Comment by bewing** [comment]
```python
In [4]: with get_network_driver('eos')('schpl03', 'bewing', p) as d:
   ...:     d.load_merge_candidate(config="banner login\nTHIS IS MY NEW \nMULTILINE BANNER\nEOF")
   ...:     print(d.compare_config())
   ...:     d.discard_config()
   ...:
@@ -1867,7 +1865,7 @@
 ip tacacs source-interface Loopback0
 !
 banner login
-THIS IS MY OLD
+THIS IS MY NEW
 MULTILINE BANNER
 EOF
 !
```

**Comment by bewing** [comment]
@dbarrosop Thoughts on this approach, or should we detect HEREDOC and handle the conversion to `{"cmd": command, "input": banner}` in NAPALM instead of having pyeapi convert it?

**Comment by bewing** [comment]
This is required to allow input of multiline commands (banner *, SSL certificates, SSH keys, etc) in `load_merge_candidate()` and `load_replacement_candidate()`.  Currently, the eAPI parser will fail on HEREDOC input unless the command and input are passed together in a single JSON RPC command.

Converting multiple lines into a single string in the format "<command> MULTILINE <lines including newlines>" allows pyeapi to detect this and use the correct JSON RPC command

**Comment by dbarrosop** [comment]
This is terrible... Could you document this in the caveats section, please?

**Comment by bewing** [comment]
TODO:
Review SSL certificates, which apparently have TWO HEREDOCs for a single command.

**Comment by dbarrosop** [comment]
What's the status of this then? Ready to merge or are you waiting on @ktbyers' project to test it?

**Comment by bewing** [comment]
Standalone test added, I think ready to merge.

**Pull request merged**
