### PR TITLE
Added get_config method

### PR DESCRIPTION
**Pull request by dbarrosop**
Related to napalm-automation/napalm-base#65

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Hmm.. that is not quite accurate as all except ibm and ros implement now ```get_config``` (nxos with the next release). But that's fine, will revisit that later.

**Comment by dbarrosop** [comment]
Yeah, there was another PR fixing that, I was mostly merging PRs and fixing conflicts. This is the result after fixing conflicts and merging PRs:

https://github.com/napalm-automation/napalm/blob/master/docs/support/index.rst

Isn't that one accurate?

**Comment by mirceaulinic** [comment]
Looks good @dbarrosop :)

**Comment by dbarrosop** [comment]
Great! Thx for confirming

**Pull request merged**
