### PR TITLE
Defined get_interfaces_ip() method for JunOS, NXOS, EOS & IOS-XR

### PR DESCRIPTION
**Pull request by mirceaulinic**
Child of #154

### CODE REVIEW

**Comment by dbarrosop** [comment]
I will wait on this one until you implement the same data structure as in #173.

**Comment by mirceaulinic** [comment]
Sure, just allow us a couple of days. It is waiting in the queue :)

**Comment by mirceaulinic** [comment]
@dbarrosop Done.

**Comment by dbarrosop** [comment]
Could you rebase again, please?

**Comment by mirceaulinic** [comment]
Rebased get_interfaces_ip

**Comment by dbarrosop** [comment]
This is sad... Can you fix the conflict again? Could you also enable the test for the new method?

**Comment by mirceaulinic** [comment]
Hmm... interesting how tests for ARP failed here although they passed on #196. Unfortunately cannot dig more right now, will have a look ASAP.

**Comment by mirceaulinic** [comment]
I do not see why the tests would fail here although on other -- inclusively on #197 now they seem to be fine (https://travis-ci.org/napalm-automation/napalm/builds/110770807#L647). Any clues?

**Comment by mirceaulinic** [comment]
Found the problem! I will need to submit another PR soon that must be merged before any other.

**Comment by dbarrosop** [comment]
No problem. Just reference it here so we know which one it is.

**Comment by mirceaulinic** [comment]
#198 will solve the problems with ARP and LLDP getters

**Comment by mirceaulinic** [comment]
One more ready to go :)

**Pull request merged**
