### PR TITLE
Added Remote Management IP address to Show LLDP Neighbors detail IOS

### PR DESCRIPTION
**Pull request by jmcgrath207**
I added the Variable Remote Management IP address for the  Show LLDP Neighbors detail on the IOS TextFSM template.

I know I have to add the test for this still, but I wanted to know if this is correct format first since I had to remove `-> Record` inorder for this to work correctly.

**Orignal Text**

```
R1#show lldp neighbors detail 
------------------------------------------------
Local Intf: Gi0/0
Chassis id: 0c87.fc76.2100
Port id: Gi0/0
Port Description: GigabitEthernet0/0
System Name: R3.test.com

System Description: 
Cisco IOS Software, IOSv Software (VIOS-ADVENTERPRISEK9-M), Version 15.6(2)T, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2016 by Cisco Systems, Inc.
Compiled Tue 22-Mar-16 16:19 by prod_rel_team

Time remaining: 96 seconds
System Capabilities: B,R
Enabled Capabilities: R
Management Addresses:
    IP: 10.161.105.84
Auto Negotiation - not supported
Physical media capabilities - not advertised
Media Attachment Unit type - not advertised
Vlan ID: - not advertised
          

Total entries displayed: 1
```

**Output**

```python
{'GigabitEthernet0/0': [{'remote_chassis_id': '0c87.fc76.2100', 'remote_port': 'Gi0/0', 'remote_port_description': 'GigabitEthernet0/0', 'remote_system_name': 'R3.test.com', 'remote_system_description': 'Cisco IOS Software, IOSv Software (VIOS-ADVENTERPRISEK9-M), Version 15.6(2)T, RELEASE SOFTWARE (fc2)', 'remote_system_capab': 'B,R', 'remote_system_enable_capab': 'R', 'remote_management_ip_address': '10.161.105.84', 'parent_interface': 'N/A'}]}
```

### CODE REVIEW

**Comment by ktbyers** [comment]
John, is this for use outside of napalm? We don't use the management address field?

**Comment by jmcgrath207** [comment]
Hey Kirk,

No, this was a change I had to make to get those remote IP address from their LLDP neighbors.  This would allow me to discover managed  IP address quickly and ensure that LLDP is work on the remote end.

This commit is just to expand the functionality of `def get_lldp_neighbors_detail` in IOS.py
by adding  `Management Addresses` to  the TexFSM parser and have it return  back to it's orignal dictionary form.

Let me know if you neeed more informaton.

Thank you,

John


This is something I've created to resolve

**Comment by ktbyers** [comment]
@jmcgrath207 Your change would not actually add the 'remote_management_ip_address' into the napalm getter. It would only add it into the TextFSM parser for IOS. 

NAPALM further selects only certain data from that output. So that 'remote_management_ip_address' would not actually be in the output data from napalm's getter. Correct me if this is inconsistent with something you see, but I am pretty sure that is right.

```python
{'GigabitEthernet0/0': [{'parent_interface': 'N/A',
                         'remote_chassis_id': '0c87.fc76.2100',
                         'remote_management_ip_address': '10.161.105.84',
                         'remote_port': 'Gi0/0',
                         'remote_port_description': 'GigabitEthernet0/0',
                         'remote_system_capab': 'B,R',
                         'remote_system_description': 'Cisco IOS Software, '
                                                      'IOSv Software '
                                                      '(VIOS-ADVENTERPRISEK9-M), '
                                                      'Version 15.6(2)T, '
                                                      'RELEASE SOFTWARE (fc2)',
                         'remote_system_enable_capab': 'R',
                         'remote_system_name': 'R3.test.com'}]}
```

Also note, in order to do this change we would have to do it across all of the napalm core platforms (EOS, Junos, nxos/nxos_ssh, ios, iosxr). In other words, this would change the returned data structure so it would require the change to be implemented across all platforms.

And we probably should agree on doing it before hand as it is quite a bit of work.

**Comment by jmcgrath207** [comment]
@ktbyers Thanks for taking a look at this. So I am having an issue finding these getters functions. I've checked the `base.py class NetworkDriver` and it doesn't seem to be there. I assume I am missing something here but it appears that the abstraction is done by the individual network drivers themselves by naming the functions with common names versus being done at a parent level.

Regardless if that is true or not, I agree with you that we want the same functionality into all of the napalm core platforms (EOS, Junos, nxos/nxos_ssh, ios, iosxr). I will have to research if I can simulate these devices but I am more than happy to add these changes to the pull request.

As for the change itself, it appears to work fine when `lldp_Neighbors = device.get_lldp_neighbors_detail()` is executed and it gives me this output.


```
{'GigabitEthernet0/0': 

[
    {'remote_chassis_id': '0c87.fc76.2100', 
    'remote_port': 'Gi0/0', 
    'remote_port_description': 'GigabitEthernet0/0', 
    'remote_system_name': 'R3.test.com', 
    'remote_system_description': 'Cisco IOS Software, IOSv Software (VIOS-ADVENTERPRISEK9-M), Version 15.6(2)T, RELEASE SOFTWARE (fc2)', 
    'remote_system_capab': 'B,R', 
    'remote_system_enable_capab': 'R', 
    'remote_management_ip_address': '10.161.105.84', 
    'parent_interface': 'N/A'}
    ]
}

```

**Comment by ktbyers** [comment]
@jmcgrath207 I think we should open an issue on this and close this PR.

The process for doing this is:
1. Get agreement that we are going to change the getter by adding a new field (in the issue).
2. Update napalm base.py to reflect this.
3. Update some set of drivers including unit tests to add the new field.

One of the key premises of napalm is to try to maintain uniformity across platforms for a given data structure so this is a bigger change than it initially appears.

**Comment by mirceaulinic** [comment]
Closing due to lack of activity. Will reopen (or review a separate PR). once we have an agreement on how to proceed.

**Pull request closed without merging**
