### PR TITLE
Fix cmd_verify and null character on NX-OS

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@xschlef Can you test this fix?

**Comment by xschlef** [comment]
you have a typo in line 509. command_verify should be cmd_verify.
If I change it manually then everything seems to work ok with paramiko 3.1

**Comment by ktbyers** [comment]
@xschlef Ooops, that was dumb...let me fix. Thanks for pointing that out.

**Comment by ktbyers** [comment]
@mirceaulinic You good with this change?

**Pull request merged**
