### PR TITLE
fix issue #1597

### PR DESCRIPTION
**Pull request by wasabi222**

### CODE REVIEW

**Comment by ktbyers** [comment]
Which version of Juniper PyEZ library do you have installed?

**Comment by ktbyers** [comment]
This requires Juniper 2.6.3 PyEZ:

[Release 2.6.3](https://github.com/Juniper/py-junos-eznc/releases/tag/2.6.3)

**Review by mirceaulinic — CHANGES_REQUESTED** [review]
Like Kirk mentioned, what we probably want is to pin to `junos-eznc>=2.6.3`

**Comment by mirceaulinic** [comment]
Replaced by #1608.

**Pull request closed without merging**
