### PR TITLE
Turning napalm into a metapackage

### PR DESCRIPTION
**Pull request by dbarrosop**
This PR turns `napalm` into a 'metapackage'. From a user perspective, nothing should change. From a code perspective this means that napalm doesn't have code anymore and it just leverages on the other individual repos.

`Napalm` should contain only the documentation, guidelines and serve as a single entry point to get napalm fully deployed.

@fooelisa @mirceaulinic @ktbyers would you mind testing this PR? If you have some code that uses napalm today I would appreciate if you could try to run it installing napalm from my fork.

### CODE REVIEW

**Comment by mirceaulinic** [comment]
@dbarrosop Fantastic! I will test it this week and I will come back with a feedback!

**Comment by mirceaulinic** [comment]
@dbarrosop I am not yet comfortable with the new method ```get_module()```, but when trying to load the driver for IOS-XR, did not work (is it caching somehow the available packages or so?). I needed to import ```napalm_iosxr``` and only afterwards it worked. It'a minor issue, but an annoying issue. Hope I won't see it again!

```
>>> from napalm import get_network_driver
>>> d = get_network_driver('junos')
>>> d = get_network_driver('iosxr')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/napalm_base/__init__.py", line 167, in get_network_driver
    mod = _load_module(_napalm_namespace(module))
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/napalm_base/__init__.py", line 94, in _load_module
    mod = _import_module(name)
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/napalm_base/__init__.py", line 52, in _import_module
    fhandle, path, descr = imp.find_module(part, path)
ImportError: No module named napalm_iosxr
>>> import napalm_iosxr
>>> d = get_network_driver('iosxr')
>>>
```

Weird, isn't it? And the same happens with the others...

I tested so far napalm-junos, seems fine, but feels slower (although I don't see an obvious reason why).

**Comment by dbarrosop** [comment]
That's super weird. Is that a new `venv`? Might be some namespace collision if you are reusing a previous venv. It certainly works for me with a brand new `venv`:

```
(test) ➜  ~ python
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from napalm import get_network_driver
>>> get_network_driver('iosxr')
<class napalm_iosxr.iosxr.IOSXRDriver at 0x1096442c0>
>>> get_network_driver('eos')
<class napalm_eos.eos.EOSDriver at 0x109704d50>
>>> get_network_driver('junos')
<class napalm_junos.junos.JunOSDriver at 0x109df2598>
>>> get_network_driver('pluribus')
<class napalm_pluribus.pluribus.PluribusDriver at 0x109df2b48>
>>> get_network_driver('ibm')
<class napalm_ibm.ibm.IBMDriver at 0x109ee6940>
```

That's even weirder but let's fix first the first problem before going to this one. Might be related. It certainly doesn't make sense as we just changed namespaces, it is the same exact code.

**Comment by mirceaulinic** [comment]
@dbarrosop yes, it's a new venv.

When installing:
```
Searching for napalm-junos
Reading https://pypi.python.org/simple/napalm-junos/
Best match: napalm-junos 0.1.1
Downloading https://pypi.python.org/packages/source/n/napalm-junos/napalm-junos-0.1.1.tar.gz#md5=a60fabc75907faa0a7537d62ff72e9d8
Processing napalm-junos-0.1.1.tar.gz
Writing /tmp/easy_install-xrJbtj/napalm-junos-0.1.1/setup.cfg
Running napalm-junos-0.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xrJbtj/napalm-junos-0.1.1/egg-dist-tmp-6PCnR9
warning: no files found matching 'napalm_junos/utils/textfsm_templates/*.tpl'
zip_safe flag not set; analyzing archive contents...
napalm_junos.utils.junos_views: module references __file__
creating /usr/local/salt/virtualenv/lib/python2.7/site-packages/napalm_junos-0.1.1-py2.7.egg
Extracting napalm_junos-0.1.1-py2.7.egg to /usr/local/salt/virtualenv/lib/python2.7/site-packages
Adding napalm-junos 0.1.1 to easy-install.pth file

Installed /usr/local/salt/virtualenv/lib/python2.7/site-packages/napalm_junos-0.1.1-py2.7.egg
Searching for napalm-iosxr
Reading https://pypi.python.org/simple/napalm-iosxr/
Best match: napalm-iosxr 0.1.1
Downloading https://pypi.python.org/packages/source/n/napalm-iosxr/napalm-iosxr-0.1.1.tar.gz#md5=4b4a600c495200fa550ad8cfabf4011f
Processing napalm-iosxr-0.1.1.tar.gz
Writing /tmp/easy_install-qYFAUu/napalm-iosxr-0.1.1/setup.cfg
Running napalm-iosxr-0.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-qYFAUu/napalm-iosxr-0.1.1/egg-dist-tmp-_0EASS
zip_safe flag not set; analyzing archive contents...
Moving napalm_iosxr-0.1.1-py2.7.egg to /usr/local/salt/virtualenv/lib/python2.7/site-packages
Adding napalm-iosxr 0.1.1 to easy-install.pth file
```

seems OK, but it ```napalm_iosxr``` is not under ```/usr/local/salt/virtualenv/lib/python2.7/site-packages```, while ```napalm_junos```, for example, does.

**Comment by mirceaulinic** [comment]
Reinstalled everything. There is a difference between them actually:

- napalm_junos:

```
creating /usr/local/salt/virtualenv/lib/python2.7/site-packages/napalm_junos-0.1.1-py2.7.egg
Extracting napalm_junos-0.1.1-py2.7.egg to /usr/local/salt/virtualenv/lib/python2.7/site-packages
```

- napalm_iosxr:

```
Moving napalm_iosxr-0.1.1-py2.7.egg to /usr/local/salt/virtualenv/lib/python2.7/site-packages
```

As a result, in the egg directory:

```
(virtualenv)mircea@36netops3:/usr/local/salt/virtualenv/lib/python2.7/site-packages$ ls -la | grep napalm
-rw-r--r--  1 mircea mircea    2210 Apr 13 14:01 napalm-1.0.0-py2.7.egg
drwxr-xr-x  4 mircea mircea      80 Apr 13 14:01 napalm_base-0.11.0-py2.7.egg
-rw-r--r--  1 mircea mircea   24839 Apr 13 14:01 napalm_eos-0.1.1-py2.7.egg
-rw-r--r--  1 mircea mircea   13543 Apr 13 14:01 napalm_fortios-0.1.1-py2.7.egg
-rw-r--r--  1 mircea mircea    5888 Apr 13 14:01 napalm_ibm-0.1.1-py2.7.egg
-rw-r--r--  1 mircea mircea   29874 Apr 13 14:01 napalm_ios-0.1.1-py2.7.egg
-rw-r--r--  1 mircea mircea   27730 Apr 13 14:01 napalm_iosxr-0.1.1-py2.7.egg
drwxr-xr-x  4 mircea mircea      80 Apr 13 14:01 napalm_junos-0.1.1-py2.7.egg
-rw-r--r--  1 mircea mircea   15364 Apr 13 14:01 napalm_nxos-0.1.1-py2.7.egg
-rw-r--r--  1 mircea mircea    7966 Apr 13 14:01 napalm_pluribus-0.1.1-py2.7.egg
```

Only ```napalm_base-0.11.0-py2.7.egg``` and ```napalm_junos-0.1.1-py2.7.egg``` are directories.

**Comment by dbarrosop** [comment]
That's weird, check the last two lines:

```
Moving napalm_iosxr-0.1.1-py2.7.egg to /usr/local/salt/virtualenv/lib/python2.7/site-packages
Adding napalm-iosxr 0.1.1 to easy-install.pth file
```

So it should be there. Where is it?

**Comment by dbarrosop** [comment]
Disregard my last message, that happens for doing it from the phone...

In my case:

```
➜  ~ ls -la ~/.virtualenvs/test/lib/python2.7/site-packages/ | grep napalm
-rw-r--r--   1 dbarroso  staff     41 Apr 11 12:54 napalm.egg-link
drwxr-xr-x  11 dbarroso  staff    374 Apr 11 12:54 napalm_base
drwxr-xr-x  10 dbarroso  staff    340 Apr 11 12:54 napalm_base-0.11.0.dist-info
drwxr-xr-x   8 dbarroso  staff    272 Apr 11 12:54 napalm_eos
drwxr-xr-x   9 dbarroso  staff    306 Apr 11 12:54 napalm_eos-0.1.1.dist-info
drwxr-xr-x   6 dbarroso  staff    204 Apr 11 12:54 napalm_fortios
drwxr-xr-x   9 dbarroso  staff    306 Apr 11 12:54 napalm_fortios-0.1.1.dist-info
drwxr-xr-x   6 dbarroso  staff    204 Apr 11 12:54 napalm_ibm
drwxr-xr-x   9 dbarroso  staff    306 Apr 11 12:54 napalm_ibm-0.1.1.dist-info
drwxr-xr-x   7 dbarroso  staff    238 Apr 11 12:54 napalm_ios
drwxr-xr-x   9 dbarroso  staff    306 Apr 11 12:54 napalm_ios-0.1.1.dist-info
drwxr-xr-x   7 dbarroso  staff    238 Apr 11 12:54 napalm_iosxr
drwxr-xr-x   9 dbarroso  staff    306 Apr 11 12:54 napalm_iosxr-0.1.1.dist-info
drwxr-xr-x   8 dbarroso  staff    272 Apr 11 12:54 napalm_junos
drwxr-xr-x   9 dbarroso  staff    306 Apr 11 12:54 napalm_junos-0.1.1.dist-info
drwxr-xr-x   8 dbarroso  staff    272 Apr 11 12:54 napalm_nxos
drwxr-xr-x   9 dbarroso  staff    306 Apr 11 12:54 napalm_nxos-0.1.1.dist-info
drwxr-xr-x   6 dbarroso  staff    204 Apr 11 12:54 napalm_pluribus
drwxr-xr-x   9 dbarroso  staff    306 Apr 11 12:54 napalm_pluribus-0.1.1.dist-info
```

Which version of pip do you have?

**Comment by mirceaulinic** [comment]
pip 8.1.1

**Comment by dbarrosop** [comment]
Are you actually install with pip? Because my output of `pip install napalm` doesn't look at all like yours.

**Comment by mirceaulinic** [comment]
Usually I install it with ```setup.py install``` which should be the same, if I'm now wrong.

**Comment by dbarrosop** [comment]
It doesn't look like it's the same at let, I think pip does some more stuff, can you try installing with `pip` and see if there is any difference? If it works with `pip` we should investigate why. It's probably something missing. Something else I am wondering is, if the packages are not folders, where are the files included in the MANIFEST.in?

**Comment by mirceaulinic** [comment]
When installing with ```pip install napalm``` doesn't attempt to install 0.60 from pypi?

**Comment by dbarrosop** [comment]
You can do:

```
pip install -e git+git@github.com:dbarrosop/napalm.git#egg=Package
```

That will install my fork instead of using the official repo.

**Comment by mirceaulinic** [comment]
Nice, didn't know this one! 

Meanwhile I finished testing on JunOS, IOS-XR, EOS, NXOS and Pluribus and it's just fine (at least from the library point of view). And I'm afraid I can't help more than that -- don't have any Fortios or IBM available right now, while IOS will be probably tested by @ktbyers.

@dbarrosop when we are done, before merging, could you please create a different branch/tag NAPALM 0.60 for the stable code, to be prepared to rollback in the worst case?

I am really looking forward to see the library growing again in terms of getters -- last month was wasted time from this perspective, but hopefully we'll gain speed from now on! ;)

We already have many functionalities added, a couple of bugs fixed, thus our version of NAPALM diverged again significantly.

**Comment by dbarrosop** [comment]
I agree with having something to rollback easily. I was planning to bump `napalm` to version 1.00 to make obvious the change and have something very clear for the requirements file (napalm < 1.00 is old monolithic module).

Does that mean installing with pip worked just fine? I will try to reproduce with `python setup.py install` but if it works with pip i will just create an issue instead of running around trying to fix it.

**Comment by mirceaulinic** [comment]
@dbarrosop Yes, installing with pip from git, did za job :)

**Comment by dbarrosop** [comment]
Ok, I will create an issue so we remember try to figure out at some point why it fails using the other method.

**Comment by mirceaulinic** [comment]
Perfect, thanks! :)

**Comment by ktbyers** [comment]
@dbarrosop I tested this on Cisco IOS. I didn't see any issues. I tested both from straight Python and using Ansible.

**Comment by dbarrosop** [comment]
I couldn't find any issue either. I also tried upgrading an existing `venv` and everything went fine so I am going to merge... Releasing on a Friday??? I know, I know. I am crazy XD

**Pull request merged**
