### PR TITLE
NXOS_SSH - fix crash issue in get_bgp_neighbors() 

### PR DESCRIPTION
**Pull request by FloLaco**
When address family is EVPN the `get_bgp_neighbors()` crash.
Even if l2vpn is not supported yet, we have to catch it.

```
Traceback (most recent call last):
  File "/home/florian_lacommare/script_switch/recette.py", line 9, in <module>
    print device.get_bgp_neighbors()
  File "/home/florian_lacommare/GitHub/napalm/napalm/nxos_ssh/nxos_ssh.py", line 897, in get_bgp_neighbors
    bgp_dict.update(bgp_summary_parser(bgp_section))
  File "/home/florian_lacommare/GitHub/napalm/napalm/nxos_ssh/nxos_ssh.py", line 320, in bgp_summary_parser
    afi = bgp_summary_dict['afi']
KeyError: u'afi'
```

### CODE REVIEW

**Comment by FloLaco** [comment]
I've added the support of l2vpn.
In fact, I've just added the `l2vpn` into `allowed_afi[]`. It's running well on my N9K leaf sand spines on a VXLAN fabric.

**Comment by dbarrosop** [comment]
sorry for the late reply. Would you mind adding tests?

**Comment by FloLaco** [comment]
@dbarrosop sure let me do it

**Comment by FloLaco** [comment]
@dbarrosop it's done ! tell me if you need something else.

**Pull request merged**
