### PR TITLE
Fix get_bgp_neighbors bug with received prefixes

### PR DESCRIPTION
**Pull request by ktbyers**
Fix for issue #226. Verify with end-user that it fixes his issue on both Cisco IOS and Cisco IOS-XE before merging.

### CODE REVIEW

**Comment by lukerussell** [comment]
Confirmed working with IOSv 15.6(1)T and IOS-XEv 03.17.00.S.

Thanks Kirk.

**Comment by dbarrosop** [comment]
@ktbyers can you send the same PR to https://github.com/napalm-automation/napalm-ios? Main IOS code will be there. I will probably start working into turning this into a metapackage this weekend so next release of napalm will contain no code.

**Comment by ktbyers** [comment]
@dbarrosop Can you merge this? It should be good to go. I am pretty sure it is right. Bug in my regex processing that unit testing didn't catch.

**Comment by dbarrosop** [comment]
Please, send the PR to `napalm-ios`. I don't want to merge new code here as I am going to turn this into a metapackage for the next release. BTW, I thought the discovery code was going to live in `netmiko`, which I think completely makes sense.

**Comment by ktbyers** [comment]
This was committed to napalm-ios.

**Pull request closed without merging**
