### PR TITLE
ios get_bgp_neighbors vrf and safi aware

### LINKED ISSUE #685: BGP multiple address families problem on IOS
On Cisco Catalyst 6800 (IOS 15.2(1)SY1a):

If my BGP configuration includes IPv4 unicast and multicast address family, this results in following error:

`FAILED! => {"changed": false, "msg": "[bgp_neighbors] cannot retrieve device data: "}`

If I add both afi address families I get around this limitation
```
--- orig/ios.py	2018-03-21 11:08:30.000000000 +0100
+++ ios.py	2018-03-21 11:20:55.000000000 +0100
@@ -1226,7 +1226,7 @@

         Currently no VRF support. Supports both IPv4 and IPv6.
         """
-        supported_afi = ['ipv4', 'ipv6']
+        supported_afi = ['ipv4 unicast', 'ipv6 unicast', 'ipv4 multicast', 'ipv6 multicast']

         bgp_neighbor_data = dict()
         bgp_neighbor_data['global'] = {}
@@ -1238,8 +1238,9 @@
         # get neighbor output from device
         neighbor_output = ''
         for afi in supported_afi:
-            cmd_bgp_neighbor = 'show bgp %s unicast neighbors' % afi
+            cmd_bgp_neighbor = 'show bgp %s neighbors' % afi
             neighbor_output += self._send_command(cmd_bgp_neighbor).strip()
+
             # trailing newline required for parsing
             neighbor_output += "\n"

@@ -1247,7 +1248,7 @@
         parse_summary = {
             'patterns': [
                 # For address family: IPv4 Unicast
-                {'regexp': re.compile(r'^For address family: (?P<afi>\S+) '),
+                {'regexp': re.compile(r'^For address family: (?P<afi>\S+\s\S+)'),
                  'record': False},
                 # Capture router_id and local_as values, e.g.:
                 # BGP router identifier 10.0.1.1, local AS number 65000
@@ -1322,7 +1323,7 @@
                  'record': False},
                 # Capture AFI and SAFI names, e.g.:
                 # For address family: IPv4 Unicast
-                {'regexp': re.compile(r'^\s+For address family: (?P<afi>\S+) '),
+                {'regexp': re.compile(r'^\s+For address family: (?P<afi>\S+\s\S+)'),
                  'record': False},
                 # Capture current sent and accepted prefixes, e.g.:
                 #     Prefixes Current:          637213       3142 (Consumes 377040 bytes)
```

### PR DESCRIPTION
**Pull request by pehruby**
address_family name in json output contains both afi and safi now. ie 'ipv4 unicast'. Therefore getter is able to distinguish for example between 'ipv4 unicast' and 'ipv4 multicast'
Fixes #685

### CODE REVIEW

**Comment by pehruby** [comment]
If backward compatibility is necessary I can change the code so that string 'ipv4' and 'ipv6' will be used for 'ipv4 unicast' and 'ipv6 unicast' AFIs.
``` json
"address_family": {
                    "ipv4": {
                        "received_prefixes": 2,
                        "accepted_prefixes": 2,
                        "sent_prefixes": 1
                    },
                    "ipv6": {
                        "received_prefixes": 0,
                        "accepted_prefixes": 0,
                        "sent_prefixes": 0
                    },
                    "ipv4 multicast": {
                        "received_prefixes": 1,
                        "accepted_prefixes": 1,
                        "sent_prefixes": 0
                    }
                }
```

**Comment by mirceaulinic** [comment]
Hey @pehruby, sorry for taking so long to review this PR. It looks like there's a small conflict, could you resolve that please, and then we should be able to get this in.

**Comment by pehruby** [comment]
Hi @mirceaulinic. I resolved the conflict. Please let me know if it is OK now.

**Comment by mirceaulinic** [comment]
Yes, looks good. Thanks @pehruby!

**Pull request merged**
