### PR TITLE
fix address_family in Junos get_bgp_neighbors()

### PR DESCRIPTION
**Pull request by ckishimo**
I'd like to understand what is the correct output when running `get_bgp_neighbors()` in Junos. 
With the following input data:
```
carles@vmx# run show bgp summary    
Groups: 1 Peers: 1 Down peers: 0
Table          Tot Paths  Act Paths Suppressed    History Damp State    Pending
inet.0               
                       2          2          0          0          0          0
bgp.l3vpn.0          
                       4          0          0          0          0          0
inet6.0              
                       0          0          0          0          0          0
Peer                     AS      InPkt     OutPkt    OutQ   Flaps Last Up/Dwn State|#Active/Received/Accepted/Damped...
192.168.2.15          65002         61         54       0       3        5:59 Establ
  inet.0: 2/2/2/0
  bgp.l3vpn.0: 0/4/4/0
  inet6.0: 0/0/0/0
  vrf.inet.0: 0/3/3/0
  vrf2.inet.0: 0/1/1/0

```
the following output is returned by `get_bgp_neighbors()`:
```
{
    "global": {
        "peers": {
            "192.168.2.15": {
                "address_family": {
                    "ipv4": {
                        "accepted_prefixes": 1, 
                        "received_prefixes": 1, 
                        "sent_prefixes": 0
                    }, 
                    "ipv6": {
                        "accepted_prefixes": 0, 
                        "received_prefixes": 0, 
                        "sent_prefixes": 0
                    }, 
                    "l3vpn": {
                        "accepted_prefixes": 4, 
                        "received_prefixes": 4, 
                        "sent_prefixes": 1
                    }
                }, 

```
What should be the counters for the `ipv4 address family` ? the counters for the `inet.0` table only ? do we skip the contents of the `routing-instances` called `vrf` and `vrf2`?
This PR modifies the output, so a different entry is created per VRF:
```
{
    "global": {
        "peers": {
            "192.168.2.15": {
                "address_family": {
                    "bgp.l3vpn": {
                        "accepted_prefixes": 4, 
                        "received_prefixes": 4, 
                        "sent_prefixes": 1
                    }, 
                    "ipv4": {
                        "accepted_prefixes": 2, 
                        "received_prefixes": 2, 
                        "sent_prefixes": 1
                    }, 
                    "ipv6": {
                        "accepted_prefixes": 0, 
                        "received_prefixes": 0, 
                        "sent_prefixes": 0
                    }, 
                    "vrf.inet": {
                        "accepted_prefixes": 3, 
                        "received_prefixes": 3, 
                        "sent_prefixes": 0
                    }, 
                    "vrf2.inet": {
                        "accepted_prefixes": 1, 
                        "received_prefixes": 1, 
                        "sent_prefixes": 0
                    }
                }, 

```
Tests are of course broken with this PR. Please let me know which counters should be reported. Thanks
This is the same question asked in https://github.com/napalm-automation/napalm-junos/pull/217, now I found the time to have a more clear (I hope) example

### CODE REVIEW

**Comment by dbarrosop** [comment]
Yes, this method doesn't support routing instances/VRFs so all the info should come from inet and inet6

**Comment by ckishimo** [comment]
@dbarrosop then there is a bug that needs to be fixed, as the `ipv4` counters are reporting the counters from the last routing instances `0/1/1/0` instead of the `inet.0` table ` 2/2/2/0` ?

**Comment by ckishimo** [comment]
@dbarrosop I updated the PR so the routing instances/VRF are skipped, and the counters should be correct now. The tests are still failing though, I believe because there are `routing_instances` defined in the tests so the counters are not correct.

Please advise if this is the desired behavior and I will update the tests. It's confusing because if the `routing_instances/VRF` are not supported, they are parsed in the `_get_address_family` function.
Thanks

**Comment by dbarrosop** [comment]
Yeah, no method should mix multiple VRF/routing instances. Either we support them and differentiate them or we return the default/global one.

Thanks!

**Comment by ckishimo** [comment]
@dbarrosop After checking the code more carefully and the mocked data I realized the routing instances are supported, but there is a case that is not. I'm sorry to have confused you...

To document the problem I created some BGP sessions using 2 virtual MX. Here are the sessions on one router:
```
ckishimo@VMX> show bgp summary 
Groups: 3 Peers: 3 Down peers: 0
Table          Tot Paths  Act Paths Suppressed    History Damp State    Pending
inet.0               
                       2          2          0          0          0          0
bgp.l3vpn.0          
                       4          0          0          0          0          0
inet6.0              
                       0          0          0          0          0          0
Peer                     AS      InPkt     OutPkt    OutQ   Flaps Last Up/Dwn State|#Active/Received/Accepted/Damped...
10.2.1.254            65006         27         34       0       1        9:01 Establ
  frontend.inet.0: 0/5/5/0
  frontend.inet6.0: 0/6/0/0
192.168.2.15          65002         54         49       0       1        9:01 Establ
  inet.0: 2/2/2/0
  bgp.l3vpn.0: 0/4/4/0
  inet6.0: 0/0/0/0
  vrf.inet.0: 0/3/3/0
  vrf2.inet.0: 0/1/1/0
fd:1:2:3::2           65006         23         31       0       1        9:01 Establ
  frontend.inet6.0: 6/6/6/0
```
The output returned by napalm with this PR is:
```
{
    "frontend": {
        "peers": {
            "10.2.1.254": {
                "address_family": {
                    "ipv4": {
                        "accepted_prefixes": 5, 
                        "received_prefixes": 5, 
                        "sent_prefixes": 5
                    }, 
                    "ipv6": {
                        "accepted_prefixes": 0, 
                        "received_prefixes": 6, 
                        "sent_prefixes": 1
                    }
                }, 
                "description": "", 
                "is_enabled": true, 
                "is_up": true, 
                "local_as": 65005, 
                "remote_as": 65006, 
                "remote_id": "10.2.1.254", 
                "uptime": 489
            }, 
            "fd:1:2:3::2": {
                "address_family": {
                    "ipv4": {
                        "accepted_prefixes": -1, 
                        "received_prefixes": -1, 
                        "sent_prefixes": -1
                    }, 
                    "ipv6": {
                        "accepted_prefixes": 6, 
                        "received_prefixes": 6, 
                        "sent_prefixes": 1
                    }
                }, 
                "description": "", 
                "is_enabled": true, 
                "is_up": true, 
                "local_as": 65005, 
                "remote_as": 65006, 
                "remote_id": "10.2.1.254", 
                "uptime": 489
            }
        }, 
        "router_id": "10.2.1.253"
    }, 
    "global": {
        "peers": {
            "192.168.2.15": {
                "address_family": {
                    "ipv4": {
                        "accepted_prefixes": 2, 
                        "received_prefixes": 2, 
                        "sent_prefixes": 1
                    }, 
                    "ipv6": {
                        "accepted_prefixes": 0, 
                        "received_prefixes": 0, 
                        "sent_prefixes": 0
                    }
                }, 
                "description": "", 
                "is_enabled": true, 
                "is_up": true, 
                "local_as": 65001, 
                "remote_as": 65002, 
                "remote_id": "192.168.2.15", 
                "uptime": 489
            }
        }, 
        "router_id": "192.168.2.16"
    }
}
```
Now the counters for the `accepted/received/sent` prefixes should be correct with this PR. The data in the example above is now included in another test

What is not working/supported are all tables other than `inet.0` or `inet6.0` in the master routing-instance. So in our example:
```
192.168.2.15          65002         54         49       0       1        9:01 Establ
  inet.0: 2/2/2/0
  bgp.l3vpn.0: 0/4/4/0
  inet6.0: 0/0/0/0
  vrf.inet.0: 0/3/3/0
  vrf2.inet.0: 0/1/1/0
```
The tables like `evpn` or `bgp.l3vpn` or `vrf/vrf2` are not supported. They were messing up with the `inet.0` and `inet6.0` counters which were not correct. To fix that in the code I had to pass the `instance` to the `_get_address_family()` function, so I could decide how to get the `address_family`

For the existing tests I only had to update the counters that were wrong, the rest of routing-instances are all still there!

Hope it's clear now... Pls let me know otherwise and sorry again for the confusion. Thanks!

**Comment by dbarrosop** [comment]
Awesome job!

**Pull request merged**
