### PR TITLE
Set next hop to something valid for vxlan routes

### PR DESCRIPTION
**Pull request by malanovo**
This is a small change that stops Napalm from bombing out on EOS when attempting a get_route_to() on a VXLAN route, and inserts some values that make it useful.  The next hop is set to the IP of the destination VTEP, and the exit interface is set to vxlan1.  Granted we're assuming the interface name will be vxlan1, but at the moment, that's all it can be on EOS.  It might need alteration in the future if Arista changes that.

### CODE REVIEW

**Review by mirceaulinic — COMMENTED** [review]
Looks good @malanovo, I think your changes make sense. Would you also be able to add a test case for this? Thanks.

**Comment by malanovo** [comment]
Sure, I can work on that.  I've got several devices I can pull from for an example.

**Comment by malanovo** [comment]
Test case has been added.  Please note that the test case relies on the fix for issue #1069 having been applied (which was just recently merged into the `develop` branch).

**Review by mirceaulinic — APPROVED** [review]
Looks good to me. Thanks @malanovo!

**Pull request merged**
