### PR TITLE
Update optional_args key_file documentation

### PR DESCRIPTION
**Pull request by stiltzkin10**
This is for napalm-automation/napalm-junos#145

### CODE REVIEW

**Comment by dbarrosop** [comment]
Is there any practical implication to the differences? If there is not I'd recommend to just leave one bullet to avoid confusing/scaring users.

**Comment by stiltzkin10** [comment]
Fair enough. Is this OK? Thanks.

**Comment by dbarrosop** [comment]
Yes, thanks a lot :)

**Comment by stiltzkin10** [comment]
Perfect! Thanks

**Pull request merged**
