### PR TITLE
WIP: Add a tutorial to use Napalm mock driver

### PR DESCRIPTION
**Pull request by sieben**
@anthony25 Let's work on this tutorial here so anybody can see and contribute to this tutorial.

### CODE REVIEW

**Comment by Anthony25** [comment]
@dbarrosop sure, really sorry I did not move on this documentation.

I will try to draft it next week. I was waiting to progress in another project, where I use the mock driver, to be more comfortable with writing this doc.

**Comment by dbarrosop** [comment]
> to be more comfortable with writing this doc

Don't worry about that too much. Feel free to ping me on slack (or by email or just tagging me here) as you progress or if you have any doubts and I will gladly help out.

**Comment by Anthony25** [comment]
Thanks a lot for your help!

**Comment by Anthony25** [comment]
As discussed [here](https://github.com/sieben/napalm/pull/1), I added some documentation for python only.

**Comment by sieben** [comment]
@dbarrosop done :)

**Comment by sieben** [comment]
I cannot build the documentation after rebasing. I get the following error:

```
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.6

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/Users/sieben/Library/Python/3.7/lib/python/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/Users/sieben/Library/Python/3.7/lib/python/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 396, in <module>
    build_getters_support_matrix(None)
  File "conf.py", line 376, in build_getters_support_matrix
    intermediate_result = matrix[method].get(driver, None)
KeyError: 'get_interfaces_ip_multiple_ipv6'

make: *** [html] Error 2
```

How could I reproduce your bug in local?

**Comment by ktbyers** [comment]
Looking at it...

**Comment by ktbyers** [comment]
It looks like it just doesn't like the indentation here:

```
diff --git a/docs/tutorials/mock_driver.rst b/docs/tutorials/mock_driver.rst
index 731da6fa..10facb53 100644
--- a/docs/tutorials/mock_driver.rst
+++ b/docs/tutorials/mock_driver.rst
@@ -151,8 +151,8 @@ Mock an error
 
 The `mock` driver can raise an exception during a call, to simulate an error.
 An error definition is  actually a json composed of 3 keys:
-    * `exception`: the exception type that will be raised
-    * `args` and `kwargs`: parameters sent to the exception constructor
+* `exception`: the exception type that will be raised
+* `args` and `kwargs`: parameters sent to the exception constructor
```

**Comment by Anthony25** [comment]
@sieben: Just add an empty space as I did here, and it will fix the issue: https://github.com/Anthony25/napalm/commit/46134c93aa35a2a2dfe1a9ac5ffc5693a21bef86

Removing the indent will remove the bullet points.

**Comment by sieben** [comment]
@Anthony25 Done

**Comment by Anthony25** [comment]
Thanks @sieben!
@ktbyers it should be good now.

**Comment by sieben** [comment]
@ktbyers Could this be merged?

**Comment by Anthony25** [comment]
Thanks!

**Pull request merged**
