### PR TITLE
replacing `message` with cast to `str`

### PR DESCRIPTION
**Pull request by sdanelli**
As noted [here ](https://github.com/napalm-automation/napalm/issues/652#issuecomment-366434168)

le old perl to the rescue `find . -type f -a -name '*py' -exec egrep -l 'raise.*\.message' {} + | xargs -I{} perl -wlpi -e 's/(raise.*?\()(\w+)\.message/$1str($2)/g' {}`

### CODE REVIEW

**Comment by ktbyers** [comment]
We should cast to str as that will be a unicode in Python3 and a ASCII string in Python2.

Instead we should do:

```
from napalm.base.utils import py23_compat

py23_compat.text_type(obj)
```

**Comment by sdanelli** [comment]
@ktbyers So, no problem doing this if you really want to, however can you tell me why? `.message` was a `str` and not unicode (in py2 anyways) AFAICT, and is every `str` in the codebase unicode?

**Comment by ktbyers** [comment]
Yes, every string in the code-base is unicode (well should be anyways). Obviously, things outside of NAPALM might do something unexpected.

Typecasting things as ASCII-strings has a way of causing problems latter on. 

Also I don't see a good reason for having it be an ASCII-string in PY2 and a Unicode String in PY3 (though there is a good chance it wouldn't cause any problem in this case...so it is mainly for consistency i.e. all of NAPALMs strings are unicode).

**Comment by sdanelli** [comment]
@ktbyers sounds good, if its consistent with the rest the code then it makes sense.

**Comment by ktbyers** [comment]
This PR was replaced by this one:

https://github.com/napalm-automation/napalm/pull/726

**Pull request closed without merging**
