### PR TITLE
get-vlans() getter implementation

### PR DESCRIPTION
**Pull request by ktbyers**
Made some updates to the IOS parts of the original PR.

Main update was to use `canonical_interface_name` solution that already existed and replace the interface_dict behavior you had (as these items were redundant with each other).

### CODE REVIEW

**Comment by ktbyers** [comment]
Updates to PR #927

**Comment by ktbyers** [comment]
The IOS driver has been reviewed and is good. I still need to review the NX-OS driver.

Currently, the IOS driver will do a per-vlan command which will be very slow (if "show vlan all-ports" doesn't exist). This is to capture interfaces that belong to trunks. This is going to be very slow so we might want a different solution like `show interfaces trunk` (but we probably shouldn't let this stop the getter from being merged i.e. better to have this and improve it across time).

**Comment by VictorPavlushin** [comment]
some code optimization https://github.com/ktbyers/napalm/pull/1

**Comment by ktbyers** [comment]
@VictorPavlushin FYI, that last change of yours broke the tests.

**Comment by VictorPavlushin** [comment]
> @VictorPavlushin FYI, that last change of yours broke the tests.
@ktbyers I changed the code, removed the error, and did not correct the resultant test.
https://github.com/ktbyers/napalm/pull/2

**Comment by VictorPavlushin** [comment]
All the time I forget about the duality of the code.
It's a pity that you can't use the general functions for nxos and nxos_ssh
https://github.com/ktbyers/napalm/pull/3

**Comment by VictorPavlushin** [comment]
I need a piece of code from the nxos_ssh driver namely _get_command_table from this pool to fix the error.
Error: the serial number is taken incorrectly, in particular, the "Processor Board ID" is displayed, and you need a Chassis -> serialnum:
```
show inventory
{
   "TABLE_inv": {
     "ROW_inv": [
       {
         "name": "Chassis",
         "desc": "Nexus 6001 Chassis",
         "productid": "N6K-C6001-64P",
         "vendorid": "V01",
         "serialnum": "FOC000000000"
       },
      {
        "name": "Module 1",
        "desc": "Nexus 64 Supervisor",
        "productid": "N6K-C6001-64P",
        "vendorid": "V01",
        "serialnum": "FOC11111111"
      },
.....
```
simpler device:
```
"TABLE_inv":{
    "ROW_inv":[
    {
        "name":"\"Chassis\"",
        "desc":"\"Nexus9000 C92160YC-X chassis\"",
        "productid":"N9K-C92160YC-X",
        "vendorid":"V02",
        "serialnum":"FDO00000000"
    },
    {
        "name":"\"Slot 1\"",
        "desc":"\"48x10G + 4x40G + 2x100G Ether net Module\"",
        "productid":"N9K-C92160YC-X",
        "vendorid":"V02",
        "serialnum":"FDO00000000"
    },
......
```
I already have ready code, but I need the function _get_command_table
The error is relevant for both drivers NX-OS.

**Comment by ktbyers** [comment]
@VictorPavlushin I am not sure I am following? So you are having a separate issue on get_facts()? Assuming so, should probably have a separate discussion on it and not put it on the PR related to get_vlans().

**Comment by VictorPavlushin** [comment]
H!
What do I need to do (how to help) so that this phencinal appears in version 3.0.0?

**Comment by VictorPavlushin** [comment]
@ktbyers Or in the next version

**Comment by mirceaulinic** [comment]
For now, @VictorPavlushin can you please fix the conflicts? I think I could help with the implementation for Junos and EOS - otherwise this looks good to me.

**Comment by VictorPavlushin** [comment]
I made two request pools for this brunch, but I'm not sure if I did it right.

**Review by mirceaulinic — APPROVED** [review]
Fixed the conflicts, and removed some redundant bits of code. I think this branch is ready to go now!

**Pull request merged**
