### PR TITLE
Method get_arp_table() defined for JunOS, NXOS, EOS & IOS-XR

### PR DESCRIPTION
**Pull request by mirceaulinic**
Child of #154

### CODE REVIEW

**Comment by dbarrosop** [comment]
This one has conflicts as well.

**Comment by jejenone** [comment]
rebased and squashed

**Comment by jejenone** [comment]
Actually I don't agree with the return structure.
Interface can't be the key. An ARP table is a list of IP/MAC association - having the interface is a bonus.
This should just return a list of key/values

**Comment by mirceaulinic** [comment]
Changed output, no more conflicts, removed filters.

**Comment by dbarrosop** [comment]
Regarding the output, I don't care that much. I would like it to look like the ``get_mac_address`` method as they provide similar functionality. So as long as we have a similar output in both of them I am fine.

**Pull request merged**
