### PR TITLE
Make config lock optional on iosxr driver

### PR DESCRIPTION
**Pull request by fooelisa**

### CODE REVIEW

**Comment by fooelisa** [comment]
Hm, good question, on iosxr you are able to commit without prior locking - do we want to enforce that?

**Comment by mirceaulinic** [comment]
As far as I am concerned it is not mandatory to lock the config to be able to commit but in case you the config is not locked by default during connection time, it might be a good idea to avoid any other concomitant config change and to block the database hence lock before any load and unlock after. Does it make any sense? :)

**Comment by mirceaulinic** [comment]
Also it would be nice to unlock the device before closing connection.

**Comment by dbarrosop** [comment]
Could you also update the documentation to reflect the new option? Check #193

**Comment by fooelisa** [comment]
Since @dbarrosop approved the Junos lock/unlock change, I guess we should stay consistent wrt locking / unlocking during the commit operation. Let me add that the same way @mirceaulinic did

**Comment by fooelisa** [comment]
ready for merge

**Comment by fooelisa** [comment]
Oh gosh, my rebase here added a lot of history.... how do I squash this properly? @mirceaulinic I'm sure you know? :)

**Comment by mirceaulinic** [comment]
Since there are not conflicts, usually I just rebase -i HEAD~NUMBER_OF_COMMITS_BACKWARDS (e.g. git rebase -i HEAD~5). Keep only the first pick and replace the following with "squash" (or "s") save, exit and afterwards type only one single commit message. Sorry I am in a bit of hurry right now. Hope this helps; if not, tonight I will check it out when I have to solve other issues in #160.

**Comment by fooelisa** [comment]
Sure, no rush :)

I am wondering if it is normal for all the previous commits by others to show up in this PR after my rebase?

**Comment by jejenone** [comment]
Not normal - how did you rebase ?
You might just want to merge master into the branch and fix the conflicts in that case.

**Comment by fooelisa** [comment]
No idea! I closed this and opened another PR after some local cleanup ;)

**Pull request closed without merging**
