### PR TITLE
[DON'T MERGE] - Add VRF structure in for get_interfaces_ip

### PR DESCRIPTION
**Pull request by ktbyers**
Add VRF structure for get_interfaces_ip

### CODE REVIEW

**Comment by ktbyers** [comment]
Replaces https://github.com/napalm-automation/napalm/pull/815

**Comment by ktbyers** [comment]
Related to:

https://github.com/napalm-automation/napalm/issues/792

**Comment by ktbyers** [comment]
Items that are needed (at least longer term):
- unit tests
- getters table updated to indicate vrf support
- make sure napalm-validate works properly with getter
- make sure napalm-ansible works with getter
- make sure no issues with Salt.

**Comment by ktbyers** [comment]
@FloLaco Can you provide more details on what the issue with napalm validate is?

**Comment by ktbyers** [comment]
I think you should be able to do:

```
    _kwargs:
      vrf: whatever
```

We will need to verify this though.

**Comment by ktbyers** [comment]
@bewing Any chance of reviewing this?  Thanks.

**Comment by FloLaco** [comment]
> I think you should be able to do:
> 
> ```
>     _kwargs:
>       vrf: whatever
> ```
> We will need to verify this though.

@ktbyers I tried to add kwargs in 2 places but it does not work.
Maybe I did something wrong ...

```
    napalm_validate:
      validation_file: "{{ val_dir }}/validate-nxos_{{ site }}.yml"
      [...]
      kwargs:
        - vrf: "all"
```

or 

```
- get_ospf_neighbors:
    kwargs:
      - vrf: all
    UNDERLAY:
      global:
        peers:
         10.55.0.1: {}
         10.55.0.3: {}
```
I also tried  `_kwargs`

**Comment by ktbyers** [comment]
Put on hold as we are probably going to solve this slightly differently.

**Comment by ktbyers** [comment]
@FloLaco It should be _kwargs. 

Why are you making it a list?

```
    kwargs:
      - vrf: all
```

I think it should be:

```
    _kwargs:
         vrf: whatever
```

**Comment by FloLaco** [comment]
> @FloLaco It should be _kwargs.
> 
> Why are you making it a list?
> 
> ```
>     kwargs:
>       - vrf: all
> ```
> I think it should be:
> 
> ```
>     _kwargs:
>          vrf: whatever
> ```

I also tried it but it didn't work.
Confirm me, I need to put this in my `validation_file` like I did on my 2nd example

**Comment by ktbyers** [comment]
@FloLaco I am pretty much going from this example (and I had checked the source code last week for a different issue). See the 'ping' example.

https://napalm.readthedocs.io/en/latest/validate/

Yes, in your validation file. Here is the relevant area of the source code:

https://github.com/napalm-automation/napalm/blob/develop/napalm/base/validate.py#L192


Note, this would be a separate issue so if there is a problem here you should open a separate issue on it.

**Comment by FloLaco** [comment]
@ktbyers Thanks for the links. Ok so it should work like you said. I'll try again tomorrow and will open a new issue if it's still not working.
Thanks

**Comment by ktbyers** [comment]
Yes, sounds good. I haven't tested it so if there is an issue there...just let us know.

**Comment by FloLaco** [comment]
@ktbyers I've tested and it works.. noob error, I've edited the wrong validation_file ...

**Comment by jobec** [comment]
For nxos_ssh the below patch should work.
We're using it internally in a custom nxoss_ssh driver.
```diff
--- a/napalm/nxos_ssh/nxos_ssh.py
+++ b/napalm/nxos_ssh/nxos_ssh.py
@@ -889,7 +889,7 @@ class NXOSSSHDriver(NXOSDriverBase):
         output = self._send_command(command) # noqa
         return ntp_stats

-    def get_interfaces_ip(self):
+    def get_interfaces_ip(self, vrf=""):
         """
         Get interface IP details. Returns a dictionary of dictionaries.

@@ -920,8 +920,8 @@ class NXOSSSHDriver(NXOSDriverBase):
         }
         """
         interfaces_ip = {}
-        ipv4_command = 'show ip interface vrf default'
-        ipv6_command = 'show ipv6 interface vrf default'
+        ipv4_command = 'show ip interface vrf {}'.format(vrf or "default")
+        ipv6_command = 'show ipv6 interface vrf {}'.format(vrf or "default")
         output_v4 = self._send_command(ipv4_command)
         output_v6 = self._send_command(ipv6_command)

```

**Comment by jobec** [comment]
I've implemented the above patch in PR #877

**Comment by jobec** [comment]
@ktbyers 

From base.py:
>'vrf' of null-string will default to the global or default VRF. 'vrf' of 'all' will
> return the interface IPs for all VRFs. 'vrf' referring to a specific VRF will return
> the interface IPs of that specific VRF. In all cases the same data structure is returned
> and no reference to the VRF that was used is included in the output.

I would vote to turn this around and make the default to show from all VRFs. E.g. `vrf=''` equals `vrf=`all``.
Because:
* It looks like this is already the case for all platforms except for nxos.
* People expect to see everything by default, instead of only a subset on some platforms and all on others.
* It would mean quite some juggling to turn it around for other platforms (e.g. show only global or default VRFs).

**Comment by ktbyers** [comment]
@jobec Let me review the past history on this issue a bit. 

On the face of it that all sounds reasonable as my main concern regarding using 'all' related to backwards compatibility.

**Comment by ktbyers** [comment]
This is not being actively worked on any longer so I am going to close it.

**Pull request closed without merging**
