### PR TITLE
Pre decorator commit

### PR DESCRIPTION
**Pull request by itdependsnetworks**
ok, this is a mess, but it's a start. 

I had troubles making it a decorator, so I wanted to get something on paper to agree on, and perhaps some pointers.

### CODE REVIEW

**Comment by dbarrosop** [comment]
What is it you are trying to achieve here?

**Comment by itdependsnetworks** [comment]
https://github.com/napalm-automation/hackathon-2017/issues/4

**Comment by dbarrosop** [comment]
Ok, so if we want to go with the recorder/replayer I think we should continue the work in napalm-automation/napalm-base/pull/296.

If you just want to log for posterity what's going on do instead:

```
import logging

log_backend = logging.getLogger("napalm-backend")

...

    def __send_command(self, command):
    ...
        output = __send_command(self, command)
        log_backend.debug(command)    
```

Way simpler and cleaner and then you can just enable it and configure it by just configuring the logger.

**Comment by itdependsnetworks** [comment]
Logging in that matter does not accomplish my goals. See my comment in PR 296.

Reading the prior implementation PR, it is unclear to the reader (or at least me) what was discussed on slack and what the context of that convo was. Picking up this work seems like a much larger proposition, when in reality I was only selfishly concerned with the recording feature of it.

**Comment by dbarrosop** [comment]
well, if you want the recording capability we should continue the work previously started. This solution here is very adhoc and will probably lead to mistakes and inconsistencies.

**Comment by itdependsnetworks** [comment]
@dbarrosop 

I don't know what was decided, so there is nothing for me to continue.

**Comment by dbarrosop** [comment]
I think we should resend the recording/replayer PR to `napalm` and then take it from there. I will try to do that this week and ping you so you can comment and provide feedback/ideas to make sure it meets your needs.

**Comment by dbarrosop** [comment]
Closing, as usual feel free to comment/reopen if you don't agree with my decision or if you have something else to discuss.

**Pull request closed without merging**
