### PR TITLE
Fixes #695 - inconsistent use of domain name in LLDP

### LINKED ISSUE #695: Error for 'get_lldp_neighbors()' on 'ios'
I discovered a "strange" error while using NetBox which simply wraps around the NAPALM libraries.
This is what I encountered (I apologize for the extremely long line):

```
{
  "detail": "Error connecting to the device at 9.88.0.5: LLDP details could not determine the value of local interface:\n{'TenGigabitEthernet1/6': [{'port': 'Te1/3', 'hostname': 'bld-vwd-d35a'}], 'TenGigabitEthernet1/5': [{'port': 'xe-0/0/2', 'hostname': 'bld-vwd-d34a'}], 'TenGigabitEthernet5/4': [{'port': 'Te3/2', 'hostname': 'bld-vsl-a'}], 'TenGigabitEthernet2/3': [{'port': 'Te5/4', 'hostname': 'bld-vsd-d32b'}], 'GigabitEthernet9/16': [{'port': 'Gi2/1', 'hostname': 'bld-sc-b'}], 'GigabitEthernet8/16': [{'port': 'Gi2/1', 'hostname': 'bld-sc-a'}], 'TenGigabitEthernet1/4': [{'port': 'Eth3/1', 'hostname': 'bld-vdd-d33a'}], 'TenGigabitEthernet2/8': [{'port': 'xe-0/0/2', 'hostname': 'bld-vdd-d37b'}], 'TenGigabitEthernet2/4': [{'port': 'Eth3/1', 'hostname': 'bld-vdd-d33b'}], 'GigabitEthernet8/18': [{'port': 'Gi1/25', 'hostname': 'bld-vsd-d17a'}], 'TenGigabitEthernet1/8': [{'port': 'xe-0/0/2', 'hostname': 'bld-vdd-d37a'}], 'TenGigabitEthernet2/2': [{'port': 'Te5/4', 'hostname': 'bld-vid-31b'}], 'TenGigabitEthernet2/5': [{'port': 'xe-0/0/2', 'hostname': 'bld-vwd-d34b'}], 'TenGigabitEthernet2/6': [{'port': 'Te1/3', 'hostname': 'bld-vwd-d35b'}], 'TenGigabitEthernet5/5': [{'port': 'Te3/2', 'hostname': 'bld-vsl-b'}], 'TenGigabitEthernet1/2': [{'port': 'Te5/4', 'hostname': 'bld-vid-31a'}], 'TenGigabitEthernet1/3': [{'port': 'Te5/4', 'hostname': 'bld-vsd-d32a'}], 'TenGigabitEthernet1/1': [{'port': 'Te1/1', 'hostname': 'bld-vsc-b'}]}\n\nChassis id: 3820.56c1.4d29\nPort id: Te1/3\nPort Description: bld/vWD35a-vSCa/global\nSystem Name: bld-vwd-d35a.attmgmt.ibm.com\n\nSystem Description: \nCisco IOS Software, c6848x Software (c6848x-ADVENTERPRISEK9-M), Version 15.4(1)SY1, RELEASE SOFTWARE (fc8)\nTechnical Support: http://www.cisco.com/techsupport\nCopyright (c) 1986-2016 by Cisco Systems, Inc.\nCompiled Fri 09-Dec-16 07:37 by prod_rel_team\n\nTime remaining: 100 seconds\nSystem Capabilities: B,R\nEnabled Capabilities: B,R\nManagement Addresses:\n    IP: 9.88.1.89\n    IPV6: 2620:1F7:9C2:C388::A\nAuto Negotiation - supported, enabled\nPhysical media capabilities:\n    Other/unknown\nMedia Attachment Unit type - not advertised\nVlan ID: - not advertised\n\n"
```

I brought this issue up in the NetworkToCode Slack channel and I was asked to include the above along with the following two files for `show lldp neighbors` and `show lldp neighbors detail`:

[show_lldp_neighbors.txt](https://github.com/napalm-automation/napalm/files/1900003/show_lldp_neighbors.txt)
[show_lldp_neighbors_detail.txt](https://github.com/napalm-automation/napalm/files/1900008/show_lldp_neighbors_detail.txt)

This error is really odd because this device's "partner" (`bld-vsc-b`) is running the same code level is connected to the same basic devices, but isn't exhibiting any problems when attempting to use this method on it.

If you need any other information from me for this scenario, please let me know.
Thanks again.

### PR DESCRIPTION
**Pull request by ktbyers**
Cisco had an inconsistent use of domain name in LLDP brief (as compared to other IOS devices). This was causing a failure.

### CODE REVIEW

**Comment by bdlamprecht** [comment]
Wow, that's a great turnaround time, much better than I anticipated!

I see you changed the domain names and such, but I'd prefer to clean up some of the hostnames, IPv4 , and IPv6 addresses as well since this is going to be publicly available for the foreseeable future.

The specific strings that I'd request to be altered are the following:
`bld-XXX-XXX` to `000-XXX-XXX` (or something simliar, just remove the `bld` part)
and
`9.88.X.X` to `10.0.X.X`
as well as
`2620:1F7:` to `2001:DB8:`

I'm happy to cleanup the test data if you'd like me to. Let me know.
Thanks again!

**Comment by ktbyers** [comment]
@bdlamprecht Okay, see updated strings in the test data. Just let me know if anything else needs updated in the test data.

**Comment by ktbyers** [comment]
@bdlamprecht Okay, fixed.

**Comment by bdlamprecht** [comment]
Great, that looks good.  I appreciate it very much!

**Comment by ogenstad** [comment]
+1 from me. Ran into this issue yesterday when writing a tutorial and using an old switch. This PR fixes the issue.

Please merge. :)

**Pull request merged**
