### PR TITLE
Fix issue with LLDP neighbors when remote device lacks system name on older IOS version

### PR DESCRIPTION
**Pull request by jobec**
There is a bug where LLDP neighbors end up on the same interface when the remove device didn't have a system name and the LLDP output was missing `Local Intf` on older IOS versions.

This example returns the neighbor of interface Fa0/17 as being connected to Fa0/24.
```
Capability codes:
    (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
    (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other

Device ID           Local Intf     Hold-time  Capability      Port ID
switch1             Fa0/24         120        B               Fa0/19
480f.cf28.8a1b      Fa0/17         3601                       480f.cf28.8a1b

Total entries displayed: 2
```
```
------------------------------------------------
Chassis id: a40c.c3c1.3980
Port id: Fa0/19
Port Description: FastEthernet0/19
System Name: switch1

System Description:
Cisco IOS Software, C2960 Software (C2960-LANBASEK9-M), Version 15.0(1)SE2, RELEASE SOFTWARE (fc3)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2011 by Cisco Systems, Inc.
Compiled Thu 22-Dec-11 00:46 by prod_rel_team

Time remaining: 113 seconds
System Capabilities: B
Enabled Capabilities: B
Management Addresses:
    IP: 10.127.15.129
Auto Negotiation - supported, enabled
Physical media capabilities:
    100base-TX(FD)
    100base-TX(HD)
    10base-T(FD)
    10base-T(HD)
Media Attachment Unit type: 16
Vlan ID: 1

------------------------------------------------
Chassis id: 480f.cf28.8a1b
Port id: 480f.cf28.8a1b
Port Description - not advertised
System Name - not advertised
System Description - not advertised

Time remaining: 2787 seconds
System Capabilities - not advertised
Enabled Capabilities - not advertised
Management Addresses - not advertised
Auto Negotiation - supported, enabled
Physical media capabilities:
    1000baseT(FD)
Media Attachment Unit type - not advertised
Vlan ID: - not advertised

MED Information:

    MED Codes:
          (NP) Network Policy, (LI) Location Identification
          (PS) Power Source Entity, (PD) Power Device
          (IN) Inventory

    Inventory information - not advertised
    Capabilities:
    Device type: Endpoint Class I
    Network Policies - not advertised
    Power requirements - not advertised
    Location - not advertised


Total entries displayed: 2
```
### Output
```
get_lldp_neighbors()
----------------------------------
{'FastEthernet0/24': [{'hostname': 'switch1', 'port': 'fa0/19'},
                      {'hostname': 'N/A', 'port': '40b0.34e2.bcac'}]}

get_lldp_neighbors_detail()
----------------------------------
{'FastEthernet0/24': [{'parent_interface': 'N/A',
                       'remote_chassis_id': 'a40c.c3c1.3980',
                       'remote_port': 'Fa0/19',
                       'remote_port_description': 'FastEthernet0/19',
                       'remote_system_capab': 'B',
                       'remote_system_description': 'Cisco IOS Software, C2960 '
                                                    'Software '
                                                    '(C2960-LANBASEK9-M), '
                                                    'Version 15.0(1)SE2, '
                                                    'RELEASE SOFTWARE (fc3)',
                       'remote_system_enable_capab': 'B',
                       'remote_system_name': 'switch1'},
                      {'parent_interface': 'N/A',
                       'remote_chassis_id': '40b0.34e2.bcac',
                       'remote_port': '40b0.34e2.bcac',
                       'remote_port_description': 'N/A',
                       'remote_system_capab': 'N/A',
                       'remote_system_description': 'N/A',
                       'remote_system_enable_capab': 'N/A',
                       'remote_system_name': 'N/A'}]}
```
### Expected Output
```
get_lldp_neighbors()
----------------------------------
{'FastEthernet0/16': [{'hostname': '40b0.34e2.bcac', 'port': '40b0.34e2.bcac'}],
 'FastEthernet0/24': [{'hostname': 'xwbs032101', 'port': 'Fa0/19'}]}

get_lldp_neighbors_detail()
----------------------------------
{'FastEthernet0/16': [{'parent_interface': 'N/A',
                       'remote_chassis_id': '40b0.34e2.bcac',
                       'remote_port': '40b0.34e2.bcac',
                       'remote_port_description': 'N/A',
                       'remote_system_capab': 'N/A',
                       'remote_system_description': 'N/A',
                       'remote_system_enable_capab': 'N/A',
                       'remote_system_name': 'N/A'}],
 'FastEthernet0/24': [{'parent_interface': 'N/A',
                       'remote_chassis_id': 'a40c.c3c1.3980',
                       'remote_port': 'Fa0/19',
                       'remote_port_description': 'FastEthernet0/19',
                       'remote_system_capab': 'B',
                       'remote_system_description': 'Cisco IOS Software, C2960 '
                                                    'Software '
                                                    '(C2960-LANBASEK9-M), '
                                                    'Version 15.0(1)SE2, '
                                                    'RELEASE SOFTWARE (fc3)',
                       'remote_system_enable_capab': 'B',
                       'remote_system_name': 'xwbs032101'}]}
```

### CODE REVIEW

**Comment by jobec** [comment]
Some background by the changes I made:

Instead of trying to throw together a reverse lookup table from 2 different show commands, this code now goes by the assumption that the output of `show lldp neighbors` is in the same sequence as `show lldp neighbors detail`. Which is true for every device I tried, and also matches with the data in all test suites.

The key error was in the code before this line:
https://github.com/napalm-automation/napalm/blob/d7961e8d0efbe6db3cfd4e373edc4d3f0d54f62f/napalm/ios/ios.py#L854
Where the variable `local_intf` was:

1. Not reset on every iteration. Cause it to keep the value of the previous iteration with the example code above.
1. Had already a value because the same name is used in this for loop:
https://github.com/napalm-automation/napalm/blob/d7961e8d0efbe6db3cfd4e373edc4d3f0d54f62f/napalm/ios/ios.py#L826

**Comment by ktbyers** [comment]
@jobec How large a sample size do you have on the order of 'show lldp neighbors' being the same as 'show lldp neighbors detail'? 

That was an assumption I explicitly rejected previously as I thought it probably wouldn't be reliable enough (i.e. I didn't trust it was correct).

**Comment by ktbyers** [comment]
@jobec Yes, agreed not having Local Interface in the LLDP details makes a standalone LLDP details textfsm not very useful.

I am okay with the counting on the LLDP table order being the same between the two. It is probably the least bad option (of multiple bad options given that Local Interface is not guaranteed to be in the details output).

Yes, good point on the timing issue and different table size between LLDP and LLDP detail. I would say if Local Interface is not present in the detail and the table size is different, then we just raise an error.

Looping through all of the interfaces would be prohibitively slow. That could require hundreds of show commands per device.

**Comment by jobec** [comment]
Done. I think you can consider the entire merge request as finished.

By adding the check I also found what I think is an error in the test data.
https://github.com/napalm-automation/napalm/blob/d7961e8d0efbe6db3cfd4e373edc4d3f0d54f62f/test/ios/mocked_data/test_get_lldp_neighbors_detail/normal/show_lldp_neighbors.txt#L5-L6
Contains no empty line before `Total entries...`
Instead of changing the test data, I changed the TextFSM template to take it into account. Just in case the is actually an IOS version out there that shows it like this.

**Pull request merged**
