### PR TITLE
Adding Support For Onyx SSh in NAPALM

### PR DESCRIPTION
**Pull request by anasbadaha**
Signed-off-by: Anas Badaha <anasb@mellanox.com>

Adding Support For Onyx ssh in Napalm

### CODE REVIEW

**Comment by anasbadaha** [comment]
Hi @samerd,

Please check this PR for adding support for onyx ssh in Napalm

Anas Badaha

**Comment by samerd** [comment]
Anas,
Seems that you need to add some tests in order to pass all checks.
please add these tests.
also there are few pep8 errors that needs to be fixed

**Comment by ktbyers** [comment]
@anasbadaha I think you should do this as a napalm community driver and not as part of core-napalm.

https://github.com/napalm-automation-community

I think you should create a GitHub issue for it (in napalm repo is fine), then figure out the next steps from there.

Regards, Kirk

**Comment by anasbadaha** [comment]
Hi @ktbyers,

I have created this Issue (#932) for supporting onyx_ssh driver, and I asked @mirceaulinic, to create a new repository in order to push our code there. Is this the correct way for adding support to our driver?

Anas Badaha

**Pull request closed without merging**
