### PR TITLE
Drop PY3.7 support in napalm 5.0.0; add tests for PY3.12

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
On hold pending Juniper PyEZ bug fix for PY3.12 bug pinning ncclient.

**Comment by bewing** [comment]
Believe this is good to go with pyez 2.7.0

https://github.com/Juniper/py-junos-eznc/pull/1288/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552

**Comment by ktbyers** [comment]
Also updated repository settings to test PY3.12 (and not test PY3.7)

**Comment by ktbyers** [comment]
@bewing Do you want to approve and merge this (it doesn't like me doing it, since I created the PR).

**Comment by bewing** [comment]
Do we want to hold this and just rebase/merge right before a release?  What does our cadence look light.  Merging now would make it harder to do bugfix releases.

**Comment by ktbyers** [comment]
I am open to either way. I guess we can just limbo this one and then we can do one more 4.x.x release (if we need to).

**Review by mirceaulinic — APPROVED** [review]
Nice! 😄

**Pull request merged**
