### PR TITLE
Junos: Support interface units in get_interfaces()

### PR DESCRIPTION
**Pull request by ckishimo**
Support for interface units in Junos `get_interfaces()` only. Issue #431 
Based on the Arista example, we have to include the subinterfaces which will inherit most of the information from the physical interface except the `description` and the `is_enabled` fields. Can somebody clarify if that is enough or is there any other thing that needs to be done ? Thanks

```
    "ge-0/0/8": {
        "description": "", 
        "is_enabled": true, 
        "is_up": true, 
        "last_flapped": 12106.0, 
        "mac_address": "00:05:86:71:F9:08", 
        "speed": 1000
    }, 
    "ge-0/0/8.32767": {
        "description": "", 
        "is_enabled": true, 
        "is_up": true, 
        "last_flapped": 12106.0, 
        "mac_address": "00:05:86:71:F9:08", 
        "speed": 1000
    }, 
    "ge-0/0/9": {
        "description": "", 
        "is_enabled": true, 
        "is_up": true, 
        "last_flapped": 12106.0, 
        "mac_address": "00:05:86:71:F9:09", 
        "speed": 1000
    }, 
    "ge-0/0/9.0": {
        "description": "test test", 
        "is_enabled": true, 
        "is_up": true, 
        "last_flapped": 12106.0, 
        "mac_address": "00:05:86:71:F9:09", 
        "speed": 1000
    }, 
```

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Thanks for solving this @ckishimo.
Can you please provide the output of the existing method vs the output using this branch? This way it is going to be clear what's changed.

**Comment by dbarrosop** [comment]
LGTM, would you mind updating the tests?

**Comment by ckishimo** [comment]
Sorry for the delay....

@mirceaulinic attached the logs using the existing mocked data
[new-branch.log](https://github.com/napalm-automation/napalm/files/1492097/new-branch.log)
[current.log](https://github.com/napalm-automation/napalm/files/1492098/current.log)

@dbarrosop updated the tests for `get_interfaces`. It seems `get_network_instances` is using `get_interfaces` so the tests are failing. Can you confirm we still want the logical interfaces in the `get_network_instances` ? Thanks

**Comment by mirceaulinic** [comment]
Hi @ckishimo - sorry for late reply.
Yes, I believe we should update `get_network_instances` in that case too. In general I am no a fan of methods depending on others, but in this case I think it does make sense to have it like that. Thanks!

**Comment by ckishimo** [comment]
Note `get_facts()` also has a list with the interfaces but only the physical ones. The documentation does not specify whether logical interfaces should be listed as well, it can be done if needed...
```
get_facts()
-  interface_list: - List of the interfaces of the device
```

**Pull request merged**
