### PR TITLE
add get_arp_table() to IOS

### PR DESCRIPTION
**Pull request by ande0581**

### CODE REVIEW

**Comment by ktbyers** [comment]
@ande0581 I tried to run the unit test on this and saw the following issues.

```python
                protocol, address, age, mac, type, interface = line.split()
                try:
                    age = float(age)
```

You can't use 'type' as a variable name. That is a built-in keyword. Also the age of a mac address can come back as a '-' for MAC addresses that belong to the device.

So here is the changes that I made:

```python
                protocol, address, age, mac, eth_type, interface = line.split()
                try:
                    if age == '-':
                        age = 0
                    age = float(age)
```

Also your return format doesn't match the format specified in base.py (and consequently the unit test still fails after the above changes). From base.py this is supposed to return a list of dictionaries as follows:

```python
            [
                {
                    'interface' : 'MgmtEth0/RSP0/CPU0/0',
                    'mac'       : '5c:5e:ab:da:3c:f0',
                    'ip'        : '172.17.17.1',
                    'age'       : 1454496274.84
                },
                {
                    'interface': 'MgmtEth0/RSP0/CPU0/0',
                    'mac'       : '66:0e:94:96:e0:ff',
                    'ip'        : '172.17.17.2',
                    'age'       : 1435641582.49
                }
            ]
```

You return a dictionary, however, at not a list (at the highest level).

**Comment by ande0581** [comment]
Hi @ktbyers 

Thanks for correcting my code. I am pretty new to programming and this is the first project i have contributed to, your criticism is appreciated.

I have made the changes you pointed out and updated my pull-request. Let me know if you want to see anything else corrected.

**Comment by ktbyers** [comment]
@ande0581 It is all good, we are all trying to improve.

Let me test the updated code.

**Comment by ktbyers** [comment]
@ande0581 This all looks good to me. It passed the Unit Test against a Cisco 881 that I have.

Here is the output of the data structure from the method:

```
[{'age': 72.0,
  'interface': u'FastEthernet4',
  'ip': u'10.220.88.1',
  'mac': u'001f.9e92.16fb'},
 {'age': 0.0,
  'interface': u'FastEthernet4',
  'ip': u'10.220.88.20',
  'mac': u'c89c.1dea.0eb6'},
 {'age': 96.0,
  'interface': u'FastEthernet4',
  'ip': u'10.220.88.22',
  'mac': u'0024.97be.8577'},
 {'age': 37.0,
  'interface': u'FastEthernet4',
  'ip': u'10.220.88.28',
  'mac': u'5254.00ee.446c'},
 {'age': 24.0,
  'interface': u'FastEthernet4',
  'ip': u'10.220.88.29',
  'mac': u'5254.0098.69b6'},
 {'age': 33.0,
  'interface': u'FastEthernet4',
  'ip': u'10.220.88.30',
  'mac': u'5254.0092.13bb'},
 {'age': 23.0,
  'interface': u'FastEthernet4',
  'ip': u'10.220.88.31',
  'mac': u'5254.0001.3737'},
 {'age': 29.0,
  'interface': u'FastEthernet4',
  'ip': u'10.220.88.38',
  'mac': u'0001.00ff.0001'}]
```

You might want to rebase your code as that will make merging easier.

http://stackoverflow.com/questions/7244321/how-to-update-a-github-forked-repository

**Comment by ktbyers** [comment]
@dbarrosop @fooelisa This all looks good to me from an IOS perspective.

**Comment by dbarrosop** [comment]
Great, thanks @ktbyers! @ande0581 can you rebase the PR, there are some conflicts and I would like you to add the mocked data and the unittests as well. If you are not sure how or what to do just let us know and we will give you a hand.

**Comment by ande0581** [comment]
@dbarrosop I do not know how to do the unit tests. I see where the mock data is stored but i am not sure how the tests get run or where the assertions are taking place. If you could provide me some direction that would be awesome.

**Comment by ktbyers** [comment]
@dbarrosop @ande0581 I can probably see if I can do this on Monday or Tuesday.

**Comment by ktbyers** [comment]
@ande0581 @dbarrosop Okay, I created a PR #212 that replaces this PR. It should be essentially the same code as here (with maybe some minor lint cleanup). I added mock data and rebased it.

I also tested it both on real device and using mock.

We should close this PR and integrate the other one.

**Comment by dbarrosop** [comment]
Closed due to PR #212

**Pull request closed without merging**
