### PR TITLE
Fix router based mac address on Cisco 6500

### PR DESCRIPTION
**Pull request by ExaneServerTeam**
Fix the issues encountered on the following show mac address-table
output on Cisco 6500:

R  1821 0008.e3ff.fca8   static   No       -      Router
-> This one is parsed
R  N/A  0008.e3ff.fca8   static   No       -      Router
-> This one is not parsed as it does not belong to any vlan

### CODE REVIEW

**Comment by ExaneServerTeam** [comment]
This pull request fix the following traceback.

# ./extract-arp.py
Traceback (most recent call last):
  File "./extract-arp.py", line 57, in <module>
    interfaces_mat_l = device.get_mac_address_table()
  File "/srv/home/adm-brin-f/Devel/pythonspace/napalm/napalm/ios/ios.py", line 1973, in get_mac_address_table
    raise ValueError("Unexpected output from: {}".format(repr(line)))
ValueError: Unexpected output from: 'R  1821 0008.e3ff.fca8   static   No       -      Router'

**Comment by ktbyers** [comment]
@ExaneServerTeam Can you include the output from the following commands (not sure which one is the proper one on your system)

```
show mac-address-table
show mac address-table
```

This will allow me to add this case into the unit tests.

Feel free to obscure the mac addresses and IP addresses.

**Comment by ExaneServerTeam** [comment]
Hello,

As we are talking about our core routers, you will find next a sample with all type of interface that may be found in the show mac address-table output, with data obfuscated on our 6500.

Regards,
Frédéric

**Comment by ExaneServerTeam** [comment]
@ktbyers Following your remark I did give a look at the end of the command.
I looks like the next input, no stats or mac address count.

`*     592 0050.569d.5307  dynamic  Yes        0     Po220`
`     1117 3863.aa21.742b  dynamic  Yes       40     Gi117/1/0/1`

**Comment by ktbyers** [comment]
@ExaneServerTeam Okay, sounds good...that looks right. I actually had conflated LLDP output with the show mac output (i.e. LLDP gives you a total count at the end and show mac doesn't).

**Comment by ExaneServerTeam** [comment]
@ktbyers Hello Kirk, please let me know if you want me test on your updates.

**Comment by ktbyers** [comment]
Updated PR with some modifications here:

https://github.com/napalm-automation/napalm/pull/725

**Pull request closed without merging**
