### PR TITLE
Raise RuntimeError when NAPALM is not installed in Python 2.7 environment

### PR DESCRIPTION
**Pull request by mirceaulinic**
Comes together with https://github.com/napalm-automation/napalm/pull/268 and https://github.com/napalm-automation/napalm/pull/267 to make sure that NAPALM is used in the right environment.

### CODE REVIEW

**Comment by dbarrosop** [comment]
Good idea! : )

**Comment by dbarrosop** [comment]
However, this is probably more beneficial if we have it in `napalm_base/base.py`. That file is **always** imported no matter if we are importing a driver directly or using `napalm` or `napalm-base` as entry points.

**Comment by mirceaulinic** [comment]
You are right, I will move it to napalm-base then

**Comment by jejenone** [comment]
That will block deployment of Napalm in Nexus Open Agent Container

see http://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus5000/sw/programmability/guide/b_Cisco_Nexus_5K6K_Series_NX-OS_Programmability_Guide/open_agent_container.html

It is running a CentOS 6.7 that has python 2.6.6 only. I think if we can avoid python 2.7 specific for the moment it would be preferable.

**Comment by dbarrosop** [comment]
@jejenone problem is that the code is not guaranteed to work on python <2.7. I know the installer doesn't work properly on older versions of python.

However, being an LXC it shouldn't be easy to install python2.7 inside it. Or is Cisco limiting what you can do there somehow?

**Pull request closed without merging**
