### PR TITLE
Expand nxos commit merge rollback error

### PR DESCRIPTION
**Pull request by TomCos**
Keeping NXOS consistent with IOS and reporting that a rollback was attempted with the exception/failure.

### CODE REVIEW

**Comment by ktbyers** [comment]
I am probably going to hold off on NX-OS changes until this PR is merged:

https://github.com/napalm-automation/napalm/pull/857

Since 857 is a pretty big change, it will be easier to resolve merge conflicts in the smaller changes after that PR is merged

**Comment by ktbyers** [comment]
Unblocked :-)

**Comment by TomCos** [comment]
Just following up on this one as well.  Everything looks to be passing.

**Comment by TomCos** [comment]
@ktbyers still want this one in as well?

**Pull request merged**
