### PR TITLE
Type hinting

### PR DESCRIPTION
**Pull request by Kircheneer**
Something weird happened with #1434 so I redid the PR - again. This should be mostly free of any non-sense commits and should reflect a proper and useful implementation of type hinting for the NXOS parts of NAPALM.

### CODE REVIEW

**Comment by Kircheneer** [comment]
Anything else I can do here to help get this merged?

**Comment by ktbyers** [comment]
Yeah, don't hold this up for me...so if it is good with @mirceaulinic (then it is fine with me).

**Comment by mirceaulinic** [comment]
Hi @Kircheneer. Yes, just let me release version 3.4.0 (hopefully next week), then we can merge this and start preparing release 4.0.0. Sorry for the wait!

**Comment by Kircheneer** [comment]
Thanks @mirceaulinic. Just let me know whenever we are ready for merging, then I'll clean up the conflicting files again.

**Comment by Kircheneer** [comment]
Left with the following errors:

```
napalm/base/helpers.py:305: error: Incompatible default for argument "default" (default has type "str", argument has type "R")
napalm/base/mock.py:201: error: Module has no attribute "CommitError"
```

For the first one: The docs state explicitly that a `str` will always be returned, even though in general I though this would be a generic function. Any clues as to what degree this is true?

For the second one: I'm unsure how this got introduced - any pointers?

**Comment by Kircheneer** [comment]
Regarding the `CommitError` thing, I'm thinking that this is probably a bug Mypy uncovered. I just moved the `raise napalm.CommitError("Pending commit confirm already in process!")` line to the front of the commit_config method:
```python
    def commit_config(self, message: str = "", revert_in: Optional[int] = None) -> None:

        raise napalm.CommitError("Pending commit confirm already in process!")
        count = self._count_calls("commit_config")
        self._raise_if_closed()
        if revert_in is not None:
            if self.has_pending_commit():
                raise napalm.CommitError("Pending commit confirm already in process!")
            else:
                self._pending_commits = True
        self.merge = None
        self.filename = None
        self.config = None
        mocked_data(self.path, "commit_config", count)
```

This lead to the following unit test errors:
```
FAILED test/base/test_mock_driver.py::TestMockDriver::test_configuration_merge - AttributeError: module 'napalm' has no attribute 'CommitError'
FAILED test/base/test_mock_driver.py::TestMockDriver::test_configuration_replace - AttributeError: module 'napalm' has no attribute 'CommitError'
FAILED test/base/test_mock_driver.py::TestMockDriver::test_configuration_replace_confirm - AttributeError: module 'napalm' has no attribute 'CommitError'
```

I'll put in a fix for that into this branch if you don't mind.

About the other issue I think we need to have a synchronous discussion because that touches lots of places at once.

**Review by mirceaulinic — APPROVED** [review]
Awesome work, @Kircheneer! 🙇🏼

**Pull request merged**
