### PR TITLE
Return more specific with `get_route_to()`

### PR DESCRIPTION
**Pull request by bewing**
Update `base` and `eos` drivers to support returning more specific prefixes in `get_route_to()`

Raise NotImplementedError on drivers that implement `get_route_to()` when kwarg `longer` is `True`

### CODE REVIEW

**Comment by dbarrosop** [comment]
+1

**Comment by bewing** [comment]
I can't remember why this didn't get merged -- pretty stale at this point.  Want me to refresh and review?

**Comment by ktbyers** [comment]
@bewing Sounds good to me.

**Comment by mirceaulinic** [comment]
Hey @bewing - suppose it'd be too much to ask you to revisit this and resolve the conflicts? :sweat_smile:

**Comment by bewing** [comment]
Rebased and resolved.

**Comment by mirceaulinic** [comment]
Yay, just merged in our oldest PR. Thanks @bewing :pray:

**Pull request merged**
