### PR TITLE
added get_route_to for nxos

### PR DESCRIPTION
**Pull request by vglinskiy**
added get_route_to for nxos

### CODE REVIEW

**Comment by ktbyers** [comment]
Quite a few things in the linter are failing:

```
napalm/nxos/nxos.py napalm/nxos/nxos.py:1118:101: E501 line too long (109 > 100 characters) [pep8]
napalm/nxos/nxos.py:1118:109: E502 the backslash is redundant between brackets [pep8]
napalm/nxos/nxos.py:1119:20: E128 continuation line under-indented for visual indent [pep8]
napalm/nxos/nxos.py:1120:101: E501 line too long (106 > 100 characters) [pep8]
napalm/nxos/nxos.py:1120:62: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1120:80: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1120:102: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1121:101: E501 line too long (124 > 100 characters) [pep8]
napalm/nxos/nxos.py:1121:21: E127 continuation line over-indented for visual indent [pep8]
napalm/nxos/nxos.py:1121:37: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1121:60: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1121:81: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1121:102: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1121:121: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1125:12: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1126:12: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1127:12: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1128:12: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1129:12: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1130:12: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1131:12: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1132:12: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1133:12: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1134:12: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1135:101: E501 line too long (112 > 100 characters) [pep8]
napalm/nxos/nxos.py:1135:15: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1136:101: E501 line too long (126 > 100 characters) [pep8]
napalm/nxos/nxos.py:1136:15: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1136:69: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1136:87: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1136:107: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1137:101: E501 line too long (124 > 100 characters) [pep8]
napalm/nxos/nxos.py:1137:25: E127 continuation line over-indented for visual indent [pep8]
napalm/nxos/nxos.py:1137:42: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1137:61: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1137:80: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1137:97: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1137:120: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1138:42: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1138:63: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1138:82: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1139:15: E114 indentation is not a multiple of four (comment) [pep8]
napalm/nxos/nxos.py:1140:15: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1142:15: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1144:101: E501 line too long (108 > 100 characters) [pep8]
napalm/nxos/nxos.py:1147:78: W291 trailing whitespace [pep8]
napalm/nxos/nxos.py:1148:101: E501 line too long (129 > 100 characters) [pep8]
napalm/nxos/nxos.py:1148:126: E231 missing whitespace after ',' [pep8]
napalm/nxos/nxos.py:1150:101: E501 line too long (107 > 100 characters) [pep8]
napalm/nxos/nxos.py:1150:107: E502 the backslash is redundant between brackets [pep8]
napalm/nxos/nxos.py:1150:23: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1150:40: W605 invalid escape sequence '\s' [pep8]
napalm/nxos/nxos.py:1151:101: E501 line too long (118 > 100 characters) [pep8]
napalm/nxos/nxos.py:1151:76: E128 continuation line under-indented for visual indent [pep8]
napalm/nxos/nxos.py:1154:23: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1157:23: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1158:101: E501 line too long (101 > 100 characters) [pep8]
napalm/nxos/nxos.py:1158:27: E111 indentation is not a multiple of four [pep8]
napalm/nxos/nxos.py:1159:12: E111 indentation is not a multiple of four [pep8]
```

You will need to fix these.

Unit tests are also failing--that will need fixed.

**Comment by vglinskiy** [comment]
Hi, I modified implementation to be more like EOS one, but it looks like something is still amiss. Could you please clarify what's failing? thanks

**Comment by pehruby** [comment]
napalm/nxos/nxos.py napalm/nxos/nxos.py:1184:50: W605 invalid escape sequence '\s' [pep8]

Look at details of continuous-integration/travis-ci/pr

**Comment by ktbyers** [comment]
You should make all regular expression patterns raw strings so:

```
pattern = r"^\s.some.regex.pattern.*$"
```

**Comment by ktbyers** [comment]
I don't think this PR was ever fully passed the unit tests. I am going to close this. If someone wants to re-implement this feel free to have at it.

**Pull request closed without merging**
