### PR TITLE
add range for validate

### PR DESCRIPTION
**Pull request by itdependsnetworks**
Haven't actually tested, but in theory should work :) Will try and test over the next few days.

### CODE REVIEW

**Comment by ktbyers** [comment]
@itdependsnetworks You still working on this?

**Comment by itdependsnetworks** [comment]
Yes

**Comment by mirceaulinic** [comment]
Bump @itdependsnetworks

**Comment by itdependsnetworks** [comment]
Ok, will take a look

**Comment by mirceaulinic** [comment]
@itdependsnetworks ?

**Comment by itdependsnetworks** [comment]
Updated syntax to be `<->` as the `-` was not unique enough (getting tripped up on Port-Channel1 as an example)

I updated the tests and documentation to go with it.

**Comment by itdependsnetworks** [comment]
Should be good to go

**Pull request merged**
