### PR TITLE
Added get_vlans functionality according to issues #927

### PR DESCRIPTION
**Pull request by VictorPavlushin**
Added get_vlans functionality according to issues #927
for ios, nxos and nxos_ssh drivers

### CODE REVIEW

**Comment by VictorPavlushin** [comment]
I did this in under issues #927 .
What you want, most likely, I partially implemented here: https://github.com/Anthony25/netbox-netprod-importer/pull/22
Please write what and in what form you want.
Also what fields from which commands, because I am not a network engineer and I don’t know much.
I can also check only on Cissco equipment.

**Comment by mirceaulinic** [comment]
I don't have any strong requirements -- the structure you added would be fine by me, just thinking to engage the community and see what else would be useful to have. Either way, my suggestion wouldn't change this structure, but extend it with a few additional fields -- but we can add them later at any point. In other words, I'm totally fine to get this in as-is.
CC @ktbyers

**Comment by VictorPavlushin** [comment]
I understood you :) it was easier for me to have a technical task because I repeat that I am not a network engineer and I don’t know much :)

**Comment by VictorPavlushin** [comment]
> I like the direction, the implementation looks good for this purpose, however I believe there are few other important details that would be great to have, besides the list of interfaces, including: VLAN mode, VLAN ID (in pair with VLAN name), QinQ ID, others?

**VLAN mode** - Not many devices have FabricPath support. I have nowhere to check this configuration.

**VLAN ID (in pair with VLAN name)** - return data structure:
`{
    "1": {
        "name": "default",
        "interfaces": [
            "port-channel12",
            "port-channel100",
            "Ethernet1/15",
            "Ethernet1/21",
        ]
    },
    "161": {
        "name": "Vlan161",
        "interfaces": [
            "port-channel12",
            "port-channel22",
            "port-channel23",
            "port-channel24",
            "Ethernet1/22",
        ]
    },
    "177": {
        "name": "Vlan177",
        "interfaces": [
            "port-channel12",
            "port-channel100",
            "Ethernet1/21",
            "Ethernet1/22",
            "Ethernet1/23",
            "Ethernet1/24",
            "Ethernet1/47",
            "Ethernet1/48"
        ]
    }
}`
already contains the right information

**QinQ ID** - no way to test

Any more requests?

**Comment by ktbyers** [comment]
@VictorPavlushin @mirceaulinic 

Adding relevant discussion thread here:

https://github.com/napalm-automation/napalm/issues/919

The net effect of that 919 (IIRC) was to propose two different getters `get_vlans` and `get_interfaces_vlans`. The get_vlans would be what is here or something similar. 

The `get_interfaces_vlans` (which hasn't been built by anyone) would be more of an interface focussed getter so would include the interface mode (access, trunk, et cetera), and the VLAN(s) the port belonged to.

Not sure what was meant by this @mirceaulinic `VLAN ID (in pair with VLAN name)` (can you expand on that as I might be missing what you are interested in here)?

Q-in-Q - I would probably say we not include in this getter (i.e. that its get punted to either the other getter or that there be a Q-in-Q specific getter). 

Note, there was quite a bit of discussion of some of these topics in the thread I linked to above.

So I am fine with this overall structure. I would like to still review this getter implementation some more however.


Kirk

**Comment by ktbyers** [comment]
Some updates to IOS and get-vlans() here:

https://github.com/napalm-automation/napalm/pull/1023

I will review and potentially make some updates to the other drivers as well.

**Pull request closed without merging**
