### PR TITLE
Adding Junos MPLS LSP getters

### PR DESCRIPTION
**Pull request by ipv6freely**
This PR is to add support for a `get_mpls_lsp()` function in the junos driver. Accepts a `lsp_type` argument that allows 'ingress', 'egress', 'transit' options. If none of the three are used, all three are returned.

Returns the same data as "show mpls lsp" on a Junos device.

Tested on various MX and SRX platforms. 

Used this sample code to test:
```
#!/usr/bin/python

import os
import napalm

try:

    driver = napalm.get_network_driver('junos')

    router = '10.192.254.16'

    with driver(hostname = router, 
                username = os.environ['ADUSERNAME'],
                password = os.environ['ADPASSWORD'], 
                optional_args = {'port': 22}) as client:
        
        lsp_dict = client.get_mpls_lsp(lsp_type='')

        print(lsp_dict)

except Exception as e:
    print(f'??? Unable to connect to {router}... skipping.', e)
```

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
@ipv6freely Is this a new getter? If so was there a proposal and/or have you attempted to update base?

**Comment by ipv6freely** [comment]
@itdependsnetworks yes, its new. No there was no proposal. No updates to base.

**Comment by ipv6freely** [comment]
Base is updated, testing is complete. 
`  py27: commands succeeded
  py34: commands succeeded
  py35: commands succeeded
  py36: commands succeeded
  congratulations :)`

**Comment by dbarrosop** [comment]
Very nice job! :D

**Comment by dbarrosop** [comment]
I have a question though regarding the data. You seem to be mixing RSVP and LSP information. Ideally we would model the data based on the openconfig models:

https://ops.openconfig.net/branches/master/openconfig-network-instance.html

My main concern is that this method might fail if you are installing LSPs with a different control plane.

**Comment by mirceaulinic** [comment]
Hey @ipv6freely - did you see @dbarrosop's suggestion above? Thanks!

**Comment by mirceaulinic** [comment]
@ipv6freely if you were to continue the work on this branch, feel free to reopen.

**Pull request closed without merging**
