### PR TITLE
add get_snmp_information() method to IOS

### PR DESCRIPTION
**Pull request by ande0581**

### CODE REVIEW

**Comment by dbarrosop** [comment]
Could you add the method to base.py with a docstring describing what the method is supposed to do?

**Comment by ande0581** [comment]
docstring has been added and pushed to this branch

**Comment by mirceaulinic** [comment]
On our side, we can implement get_snmp_information() for JunOS, IOS-XR, NXOS, EOS and Pluribus.

**Comment by dbarrosop** [comment]
That would be great!

**Comment by ande0581** [comment]
Done
@mirceaulinic was this what you were asking for?

**Comment by mirceaulinic** [comment]
Yes, exactly!

**Comment by ktbyers** [comment]
I don't see any unit test for this? Has this been created?

**Comment by mirceaulinic** [comment]
No unittest at the time being. We have not yet implemented as I said in https://github.com/napalm-automation/napalm/pull/175#issuecomment-181998524. @ande0581 don't wait for us. Please submit a solution if you have time.

**Comment by ande0581** [comment]
moving this to new PR https://github.com/napalm-automation/napalm/pull/218

**Pull request closed without merging**
